In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\DataSet\customer_data.csv")

print("Shape of DataSet:", df.shape)
print("\nData Types of each column:")
print(df.dtypes)
print("\nNull Values is DataSet")
print(pd.isnull(df).sum())
print("\n Description of dataset ")
print(df.describe)
print('check duplicate\n')
print(df.duplicated().sum())
df.head()

Shape of DataSet: (100, 7)

Data Types of each column:
CustomerID            int64
Age                   int64
Gender                  str
Location                str
TotalPurchases        int64
TotalAmountSpent    float64
LastPurchaseDate        str
dtype: object

Null Values is DataSet
CustomerID          0
Age                 0
Gender              0
Location            0
TotalPurchases      0
TotalAmountSpent    0
LastPurchaseDate    0
dtype: int64

 Description of dataset
<bound method NDFrame.describe of     CustomerID  Age  Gender     Location  TotalPurchases  TotalAmountSpent  \
0            1   68  Female      Houston              24            595.11
1            2   35    Male      Phoenix              29           2901.57
2            3   60    Male      Phoenix              19           4109.95
3            4   63  Female      Chicago              27           2324.75
4            5   42    Male  Los Angeles              15           1122.67
..         ...  ...     ...          ...             ...               ...
95          96   41  Female      Phoenix               2            616.88
96          97   22  Female      Houston              28             66.42
97          98   60    Male      Houston               7           4966.48
98          99   67  Female      Houston              27           3982.74
99         100   26  Female      Chicago              19           3319.24

   LastPurchaseDate
0        2023-01-01
1        2023-01-08
2        2023-01-15
3        2023-01-22
4        2023-01-29
..              ...
95       2024-10-27
96       2024-11-03
97       2024-11-10
98       2024-11-17
99       2024-11-24

[100 rows x 7 columns]>
check duplicate

0

,CustomerID,Age,Gender,Location,TotalPurchases,TotalAmountSpent,LastPurchaseDate
0,1,68,Female,Houston,24,595.11,2023-01-01
1,2,35,Male,Phoenix,29,2901.57,2023-01-08
2,3,60,Male,Phoenix,19,4109.95,2023-01-15
3,4,63,Female,Chicago,27,2324.75,2023-01-22
4,5,42,Male,Los Angeles,15,1122.67,2023-01-29

In [3]:
# 	Average Purchase Value by age and gender.
df.groupby(['Gender','Age'])[['TotalAmountSpent']].mean()

            TotalAmountSpent
Gender Age
Female 18           4947.370
       20           4785.730
       21           1621.330
       22           2147.775
       24            936.070
...                      ...
Male   63           3215.760
       64           2168.900
       67            197.160
       68           3198.230
       70           1968.180

[64 rows x 1 columns]

In [4]:
# 	Total Purchase Amount by location.
df.groupby(['Location'])[['TotalAmountSpent']].sum()

             TotalAmountSpent
Location
Chicago              46500.07
Houston              80502.02
Los Angeles          31043.26
New York             31409.18
Phoenix              59964.31

In [5]:
#	Churn Rate and customer loyalty based on purchase frequency.
# customer loyalty based on purchase frequency.
df[df['TotalPurchases']>df['TotalPurchases'].mean()].shape

conditions=[
    df['TotalPurchases'] < 14,
    df['TotalPurchases'].between(14,16),
    df['TotalPurchases'] > 16
]
choices=['Low','Medium','High']

df["loyalty"] = np.select(conditions, choices, default="Unknown")
df

,CustomerID,Age,Gender,Location,TotalPurchases,TotalAmountSpent,LastPurchaseDate,loyalty
0,1,68,Female,Houston,24,595.11,2023-01-01,High
1,2,35,Male,Phoenix,29,2901.57,2023-01-08,High
2,3,60,Male,Phoenix,19,4109.95,2023-01-15,High
3,4,63,Female,Chicago,27,2324.75,2023-01-22,High
4,5,42,Male,Los Angeles,15,1122.67,2023-01-29,Medium
...,...,...,...,...,...,...,...,...
95,96,41,Female,Phoenix,2,616.88,2024-10-27,Low
96,97,22,Female,Houston,28,66.42,2024-11-03,High
97,98,60,Male,Houston,7,4966.48,2024-11-10,Low
98,99,67,Female,Houston,27,3982.74,2024-11-17,High
99,100,26,Female,Chicago,19,3319.24,2024-11-24,High

In [10]:
df["LastPurchaseDate"]

0    2023-01-01
1    2023-01-08
2    2023-01-15
3    2023-01-22
4    2023-01-29
        ...
95   2024-10-27
96   2024-11-03
97   2024-11-10
98   2024-11-17
99   2024-11-24
Name: LastPurchaseDate, Length: 100, dtype: datetime64[us]

In [11]:
#	Churn Rate

df["LastPurchaseDate"] = pd.to_datetime(df["LastPurchaseDate"])
reference_date = pd.Timestamp("2024-12-31")

days_since_last_purchase = (
    reference_date - df["LastPurchaseDate"]
).dt.days

df["Churn"] = np.where(days_since_last_purchase > 360, "Yes", "No")
df

,CustomerID,Age,Gender,Location,TotalPurchases,TotalAmountSpent,LastPurchaseDate,loyalty,Churn
0,1,68,Female,Houston,24,595.11,2023-01-01,High,Yes
1,2,35,Male,Phoenix,29,2901.57,2023-01-08,High,Yes
2,3,60,Male,Phoenix,19,4109.95,2023-01-15,High,Yes
3,4,63,Female,Chicago,27,2324.75,2023-01-22,High,Yes
4,5,42,Male,Los Angeles,15,1122.67,2023-01-29,Medium,Yes
...,...,...,...,...,...,...,...,...,...
95,96,41,Female,Phoenix,2,616.88,2024-10-27,Low,No
96,97,22,Female,Houston,28,66.42,2024-11-03,High,No
97,98,60,Male,Houston,7,4966.48,2024-11-10,Low,No
98,99,67,Female,Houston,27,3982.74,2024-11-17,High,No
99,100,26,Female,Chicago,19,3319.24,2024-11-24,High,No

In [7]:
#	Create personalized offers for the most valuable customers.
valuable_customers = df.sort_values('TotalAmountSpent',ascending=False)
valuable_customers[valuable_customers['TotalAmountSpent']>3000]

,CustomerID,Age,Gender,Location,TotalPurchases,TotalAmountSpent,LastPurchaseDate,loyalty,Churn
97,98,60,Male,Houston,7,4966.48,2024-11-10,Low,No
38,39,18,Female,Phoenix,5,4947.37,2023-09-24,Low,Yes
44,45,69,Female,Houston,11,4880.54,2023-11-05,Low,Yes
42,43,66,Female,Houston,15,4835.52,2023-10-22,Medium,Yes
40,41,20,Female,Phoenix,12,4785.73,2023-10-08,Low,Yes
78,79,43,Male,Chicago,30,4766.31,2024-06-30,High,No
63,64,57,Male,Houston,10,4532.50,2024-03-17,Low,No
33,34,43,Female,Chicago,28,4467.34,2023-08-20,High,Yes
87,88,49,Female,Houston,9,4380.05,2024-09-01,Low,No
23,24,31,Male,Los Angeles,8,4302.12,2023-06-11,Low,Yes
13,14,34,Male,Houston,28,4241.34,2023-04-02,High,Yes
88,89,58,Male,Chicago,27,4241.13,2024-09-08,High,No
79,80,22,Female,Chicago,8,4229.13,2024-07-07,Low,No
48,49,28,Male,Houston,9,4168.27,2023-12-03,Low,Yes
92,93,38,Female,Phoenix,17,4158.09,2024-10-06,High,No
2,3,60,Male,Phoenix,19,4109.95,2023-01-15,High,Yes
90,91,28,Female,Chicago,14,4096.99,2024-09-22,Medium,No
73,74,60,Male,Chicago,9,4095.17,2024-05-26,Low,No
21,22,23,Male,New York,3,4083.15,2023-05-28,Low,Yes
6,7,60,Male,Phoenix,28,4032.94,2023-02-12,High,Yes
43,44,19,Male,New York,18,4009.28,2023-10-29,High,Yes
53,54,68,Male,Houston,6,3991.65,2024-01-07,Low,No
98,99,67,Female,Houston,27,3982.74,2024-11-17,High,No
15,16,50,Male,New York,27,3873.24,2023-04-16,High,Yes
12,13,26,Female,Houston,22,3846.73,2023-03-26,High,Yes
58,59,64,Female,Phoenix,12,3801.58,2024-02-11,Low,No
17,18,42,Male,Houston,30,3788.89,2023-04-30,High,Yes
71,72,30,Female,Los Angeles,23,3697.34,2024-05-12,High,No
7,8,44,Male,Phoenix,22,3692.47,2023-02-19,High,Yes
94,95,51,Male,Houston,10,3651.81,2024-10-20,Low,No
5,6,56,Female,New York,2,3617.86,2023-02-05,Low,Yes
64,65,56,Male,Houston,26,3611.83,2024-03-24,High,No
50,51,34,Male,Houston,25,3562.49,2023-12-17,High,Yes
41,42,46,Female,Los Angeles,26,3466.96,2023-10-15,High,Yes
9,10,45,Male,Phoenix,15,3335.66,2023-03-05,Medium,Yes
99,100,26,Female,Chicago,19,3319.24,2024-11-24,High,No
11,12,63,Male,Phoenix,24,3215.76,2023-03-19,High,Yes
83,84,40,Male,Houston,10,3205.84,2024-08-04,Low,No
35,36,49,Female,Houston,25,3172.30,2023-09-03,High,Yes
67,68,64,Male,Phoenix,29,3168.03,2024-04-14,High,No
20,21,32,Female,Phoenix,12,3165.33,2023-05-21,Low,Yes
22,23,49,Male,Houston,27,3153.45,2023-06-04,High,Yes
24,25,31,Male,Phoenix,20,3058.84,2023-06-18,High,Yes

Business recommendation:

Give them exclusive discounts.

Provide VIP membership.

Offer early access to new products.

Reward them with loyalty points

In [8]:
df.groupby('loyalty')['CustomerID'].count()

loyalty
High      47
Low       44
Medium     9
Name: CustomerID, dtype: int64

In [9]:
df.groupby(['Location','Gender','Age'])[['TotalAmountSpent']].sum()

                     TotalAmountSpent
Location Gender Age
Chicago  Female 22            4229.13
                24            1872.14
                26            3319.24
                27            2846.72
                28            4096.99
...                               ...
Phoenix  Male   45            3335.66
                49            2068.66
                60            8142.89
                63            3215.76
                64            4337.80

[88 rows x 1 columns]