# 🐼 100 Pandas Practical Questions
> **Instructions:** Try to solve each question on your own. Use the hints only if you are stuck.  
> Progress: Basic → Intermediate → Advanced  
> Recommended pace: 10–15 questions per day

---

## 🔹 Section 1: Basics & Series (Q1–Q20)

---

### Q1. Create a Pandas Series from a list of integers.
> 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

---

In [357]:
import pandas as pd
import numpy as np
df=pd.Series([1,2,3,4,5,6,7,8])
print(df)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

### Q2. Create a Series from a dictionary with custom index.
> 💡 **Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.

---

In [358]:
df = pd.Series({
    'A': 'parag',
    'B': 'Sachin',
    'C': 'Dipak',
    'D': 'Rohit',
    'E': 'Virat'
})

print(df)

A     parag
B    Sachin
C     Dipak
D     Rohit
E     Virat
dtype: str

### Q3. Access elements using index labels.
> 💡 **Hint:** Use `s["label"]` for a single value, `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. Label slices are **inclusive** on both ends.

---

In [359]:
df = pd.Series({
    'A': 'parag',
    'B': 'Sachin',
    'C': 'Dipak',
    'D': 'Rohit',
    'E': 'Virat'
})

print(df)
print(df['A':'D'])
print(df['parag':'Rohit'])
print(df['B'])
df['B']='Bapu'
print(df)

A     parag
B    Sachin
C     Dipak
D     Rohit
E     Virat
dtype: str
A     parag
B    Sachin
C     Dipak
D     Rohit
dtype: str
Series([], dtype: str)
Sachin
A    parag
B     Bapu
C    Dipak
D    Rohit
E    Virat
dtype: str

### Q4. Perform arithmetic operations on a Series.
> 💡 **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.

---

In [360]:
df=pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])
print(df)

print('Division by 10')
print(df['a':'c']/10)

print('Addition of 10 \n')
print(df+10)

print('Subtraction of 10 \n')
print(df-10)

print('IntegerDivision by 2')
print(df['a':'c']//2)

print('Modulo by 2')
print(df['a':'c']%2)

print('Square of the series')
print(df**2)

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int64
Division by 10
a    0.1
b    0.2
c    0.3
dtype: float64
Addition of 10

a    11
b    12
c    13
d    14
e    15
f    16
g    17
h    18
dtype: int64
Subtraction of 10

a   -9
b   -8
c   -7
d   -6
e   -5
f   -4
g   -3
h   -2
dtype: int64
IntegerDivision by 2
a    0
b    1
c    1
dtype: int64
Modulo by 2
a    1
b    0
c    1
dtype: int64
Square of the series
a     1
b     4
c     9
d    16
e    25
f    36
g    49
h    64
dtype: int64

### Q5. Find mean, min, max of a Series.
> 💡 **Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.

---

In [361]:
df=pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])
print(df)

#mean of the series
print(df.mean())

#min of the series
print(df.min())

#max of the series
print(df.max())

#sum of the series
print(df.sum())

#median of the series
print(df.median())

#standard deviation of the series
print(df.std())

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int64
4.5
1
8
36
4.5
2.449489742783178

### Q6. Apply conditional filtering on a Series.
> 💡 **Hint:** Use a boolean mask: `s[s > 50]`. You can also chain conditions with `&` and `|`.

---

In [362]:
(df[(df>5) & (df<=8)])

f    6
g    7
h    8
dtype: int64

### Q7. Replace values in a Series.
> 💡 **Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `{old: new}` to replace multiple values at once.

---

In [363]:
df=pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])
df['b':'e']=[20,30,40,50]
print(df.replace([20,30,40,50],[2,3,4,5],inplace = True))

#by passing dictionary
df.replace({2:20,3:30,4:40,5:50},inplace = True)
print(df)

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int64
a     1
b    20
c    30
d    40
e    50
f     6
g     7
h     8
dtype: int64

In [364]:
df[['b','c','d']]=[200,00,400]
df

a      1
b    200
c      0
d    400
e     50
f      6
g      7
h      8
dtype: int64

### Q8. Convert Series data type.
> 💡 **Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.

---

In [365]:
print(df.astype('float'))
print(df.astype('int32'))
print(df.astype('str'))
print(df.astype('category'))

a      1.0
b    200.0
c      0.0
d    400.0
e     50.0
f      6.0
g      7.0
h      8.0
dtype: float64
a      1
b    200
c      0
d    400
e     50
f      6
g      7
h      8
dtype: int32
a      1
b    200
c      0
d    400
e     50
f      6
g      7
h      8
dtype: str
a      1
b    200
c      0
d    400
e     50
f      6
g      7
h      8
dtype: category
Categories (8, int64): [0, 1, 6, 7, 8, 50, 200, 400]

### Q9. Check for null values in Series.
> 💡 **Hint:** Use `.isnull()` (returns boolean Series) or `.isnull().sum()` for a count.

---

In [366]:
df=pd.Series([23,np.nan,40,50,70,np.nan,20,None])
print(df)
print('===============number of none values=====================')
print(df.isnull().sum())
print('------------null values bulean series----------')
print(df.isnull())
print('=============sum of series======')
print(df.sum())
print('=========total no of not null values==========')
print(df.notnull().sum())

0    23.0
1     NaN
2    40.0
3    50.0
4    70.0
5     NaN
6    20.0
7     NaN
dtype: float64
===============number of none values=====================
3
------------null values bulean series----------
0    False
1     True
2    False
3    False
4    False
5     True
6    False
7     True
dtype: bool
=============sum of series======
203.0
=========total no of not null values==========
5

### Q10. Fill missing values in Series.
> 💡 **Hint:** Use `.fillna(value)` for constant, `.fillna(s.mean())` for mean, `.ffill()` for forward fill, `.bfill()` for backward fill.

---

In [367]:
df=pd.Series([23,np.nan,40,50,70,np.nan,20,None])
print(df)
print(df.fillna(5))
print('------fill nan with mean value------------')
print(df.fillna(df.mean()))
print('---------fill nan value with ffill----------')
print(df.ffill())
print('---------fill nan value with ffill----------')
print(df.isnull())
print(df.bfill())

0    23.0
1     NaN
2    40.0
3    50.0
4    70.0
5     NaN
6    20.0
7     NaN
dtype: float64
0    23.0
1     5.0
2    40.0
3    50.0
4    70.0
5     5.0
6    20.0
7     5.0
dtype: float64
------fill nan with mean value------------
0    23.0
1    40.6
2    40.0
3    50.0
4    70.0
5    40.6
6    20.0
7    40.6
dtype: float64
---------fill nan value with ffill----------
0    23.0
1    23.0
2    40.0
3    50.0
4    70.0
5    70.0
6    20.0
7    20.0
dtype: float64
---------fill nan value with ffill----------
0    False
1     True
2    False
3    False
4    False
5     True
6    False
7     True
dtype: bool
0    23.0
1    40.0
2    40.0
3    50.0
4    70.0
5    20.0
6    20.0
7     NaN
dtype: float64

### Q11. Create DataFrame from a list.
> 💡 **Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. Each inner list becomes one row.

---

In [368]:
df=pd.DataFrame([[1,'Sanchita'],[2,'Bapu'],[3,'Krushna'],[4,'Jayanti'],[5,'Dipak'],[6,'Shraddha']],columns=['number','Name'],index=['E1','E2','E3','E4','E5','E6'])
df

    number      Name
E1       1  Sanchita
E2       2      Bapu
E3       3   Krushna
E4       4   Jayanti
E5       5     Dipak
E6       6  Shraddha

### Q12. Create DataFrame from a dictionary.
> 💡 **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

---

In [369]:
df=pd.DataFrame({
   'Name':['Bapu','Sanchita','Krushna','Jayanti'],
   'Marks':[23,5,67,78,]
},index=['E1','E2','E3','E4'])
print(df)

        Name  Marks
E1      Bapu     23
E2  Sanchita      5
E3   Krushna     67
E4   Jayanti     78

### Q13. Create DataFrame from list of dictionaries.
> 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

---

In [370]:
df1=pd.DataFrame([{'Sanchita':(90,80,60)},{'Bapu':80},{'parag':50}])
df1

       Sanchita  Bapu  parag
0  (90, 80, 60)   NaN    NaN
1           NaN  80.0    NaN
2           NaN   NaN   50.0

In [371]:
df1 = pd.DataFrame([
    {'Name':'Sanchita', 'Marks':90},
    {'Name':'Bapu', 'Marks':80},
    {'Name':'parag', 'Marks':50}
])
df1

       Name  Marks
0  Sanchita     90
1      Bapu     80
2     parag     50

### Q14. Display DataFrame structure (shape, columns, dtypes).
> 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.

---

In [372]:
print('shape of df1 is =\n ',df1.shape)
print()
print('column of  dataframe = \n',df1.columns)
print()
print('dtype of dataframe = \n',df1.dtypes)
print()
print('information of dataframe = \n',df1.info)
print()
print('description of Dataframe = \n',df1.describe)

shape of df1 is =
  (3, 2)

column of  dataframe =
 Index(['Name', 'Marks'], dtype='str')

dtype of dataframe =
 Name       str
Marks    int64
dtype: object

information of dataframe =
 <bound method DataFrame.info of        Name  Marks
0  Sanchita     90
1      Bapu     80
2     parag     50>

description of Dataframe =
 <bound method NDFrame.describe of        Name  Marks
0  Sanchita     90
1      Bapu     80
2     parag     50>

### Q15. Select single column from DataFrame.
> 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation).

---

In [373]:
print(df1['Name'])
print(df1.Marks)
print(df1['Marks'])

0    Sanchita
1        Bapu
2       parag
Name: Name, dtype: str
0    90
1    80
2    50
Name: Marks, dtype: int64
0    90
1    80
2    50
Name: Marks, dtype: int64

### Q16. Select multiple columns.
> 💡 **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.

---

In [374]:
print(df1[['Name','Marks']])

       Name  Marks
0  Sanchita     90
1      Bapu     80
2     parag     50

### Q17. Add new column with scalar value.
> 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically.

---

In [375]:
df1['Scalar']=10
df1

       Name  Marks  Scalar
0  Sanchita     90      10
1      Bapu     80      10
2     parag     50      10

### Q18. Add column using Series.
> 💡 **Hint:** `df["new_col"] = pd.Series([...])`. The Series index must align with the DataFrame index.

---

In [376]:
df1['Gender']=pd.Series(['Female','Male','Male','Male'])
df1

       Name  Marks  Scalar  Gender
0  Sanchita     90      10  Female
1      Bapu     80      10    Male
2     parag     50      10    Male

### Q19. Rename columns using `rename()`.
> 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

---

In [377]:
df1.rename(columns={'Scalar':'Multiplier'},inplace=True)
print(df1)

       Name  Marks  Multiplier  Gender
0  Sanchita     90          10  Female
1      Bapu     80          10    Male
2     parag     50          10    Male

### Q20. Rename multiple columns.
> 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

---

In [378]:
df1.rename(columns={'Scalar':'Multiplier','Name':'First_Name'},inplace=True)
df1

  First_Name  Marks  Multiplier  Gender
0   Sanchita     90          10  Female
1       Bapu     80          10    Male
2      parag     50          10    Male

## 🔹 Section 2: Indexing, Selection & Slicing (Q21–Q40)

---

### Q21. Select rows using `loc`.
> 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

---

In [379]:
df1.loc[1:2]

  First_Name  Marks  Multiplier Gender
1       Bapu     80          10   Male
2      parag     50          10   Male

In [380]:
df=pd.DataFrame({
   'Name':['Bapu','Sanchita','Krushna','Jayanti'],
   'Marks':[23,5,67,78,]
},index=['E1','E2','E3','E4'])
print(df)

        Name  Marks
E1      Bapu     23
E2  Sanchita      5
E3   Krushna     67
E4   Jayanti     78

In [381]:
df.loc['E1':'E3', 'Name']

E1        Bapu
E2    Sanchita
E3     Krushna
Name: Name, dtype: str

### Q22. Select rows using `iloc`.
> 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).

---

In [382]:
df.iloc[2,1:]

Marks    67
Name: E3, dtype: object

In [383]:
df.iloc[1:,:1]

        Name
E2  Sanchita
E3   Krushna
E4   Jayanti

### Q23. Access specific row and column.
> 💡 **Hint:** `df.loc[row_label, "col_name"]` or `df.iloc[row_pos, col_pos]` for a single cell.

---

In [384]:
print(df.loc['E1','Name'])
print(df.iloc[0,0])

Bapu
Bapu

### Q24. Select subset using multiple rows & columns.
> 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

---

In [385]:
print(df.loc[['E1','E3'],['Name']])
print(df.iloc[[0,2],[0]])

       Name
E1     Bapu
E3  Krushna
       Name
E1     Bapu
E3  Krushna

### Q25. Apply conditional filtering using `loc`.
> 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

---

In [386]:
print(df.loc[df['Name']=='Bapu','Name'])
df['Name']=='Bapu'

E1    Bapu
Name: Name, dtype: str

E1     True
E2    False
E3    False
E4    False
Name: Name, dtype: bool

### Q26. Slice rows using index range.
> 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or `df.loc[label1:label2]` for label-based slicing.

---

In [387]:
print(df.iloc[1:2])
print('\n==========slicing using loc=============\n')
print(df.loc[:,'Name'])

        Name  Marks
E2  Sanchita      5

==========slicing using loc=============

E1        Bapu
E2    Sanchita
E3     Krushna
E4     Jayanti
Name: Name, dtype: str

### Q27. Slice columns using labels.
> 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).

---

In [388]:
df1=df1.rename(columns={'Scalar':'Multiplier','Name':'First_Name'})
df1
df1.loc[0:2,"First_Name":"Multiplier"]

  First_Name  Marks  Multiplier
0   Sanchita     90          10
1       Bapu     80          10
2      parag     50          10

### Q28. Slice columns using position.
> 💡 **Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

---

In [389]:
df1.iloc[0:2,0:1] #last items are not included

  First_Name
0   Sanchita
1       Bapu

### Q29. Perform combined row & column slicing.
> 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

---

In [390]:
print(df.loc['E1':'E3','Name'])
df1.iloc[[0,1,2],[0,2,3]]

E1        Bapu
E2    Sanchita
E3     Krushna
Name: Name, dtype: str

  First_Name  Multiplier  Gender
0   Sanchita          10  Female
1       Bapu          10    Male
2      parag          10    Male

### Q30. Set a column as index.
> 💡 **Hint:** Use `df.set_index("col_name")`. Add `inplace=True` to modify without reassigning.

---

In [391]:
# df1.set_index('First_Name',inplace=True)
df1

  First_Name  Marks  Multiplier  Gender
0   Sanchita     90          10  Female
1       Bapu     80          10    Male
2      parag     50          10    Male

### Q31. Create hierarchical index (MultiIndex).
> 💡 **Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

---

In [392]:
df1.set_index(['Multiplier','Marks']
              )

                 First_Name  Gender
Multiplier Marks
10         90      Sanchita  Female
           80          Bapu    Male
           50         parag    Male

### Q32. Reset index.
> 💡 **Hint:** `df.reset_index()` — moves the current index back to a column. Use `inplace=True` to modify in-place.

---

In [393]:
# df1.reset_index(inplace=True)
df1

  First_Name  Marks  Multiplier  Gender
0   Sanchita     90          10  Female
1       Bapu     80          10    Male
2      parag     50          10    Male

### Q33. Reset multi-index.
> 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns.

---

In [394]:
df.reset_index(drop=False)

  index      Name  Marks
0    E1      Bapu     23
1    E2  Sanchita      5
2    E3   Krushna     67
3    E4   Jayanti     78

### Q34. Convert index to column.
> 💡 **Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.

---

In [395]:
# df1.set_index(['level_0','index'])

### Q35. Use drop option in `reset_index`.
> 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.

---

In [396]:

df1.set_index('First_Name')

            Marks  Multiplier  Gender
First_Name
Sanchita       90          10  Female
Bapu           80          10    Male
parag          50          10    Male

In [397]:
df1.reset_index(drop=False)

   index First_Name  Marks  Multiplier  Gender
0      0   Sanchita     90          10  Female
1      1       Bapu     80          10    Male
2      2      parag     50          10    Male

### Q36. Perform label-based indexing.
> 💡 **Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).

---

In [398]:
# df1.loc['Bapu']

### Q37. Perform position-based indexing.
> 💡 **Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.

---

In [399]:
df1.iloc[0]

First_Name    Sanchita
Marks               90
Multiplier          10
Gender          Female
Name: 0, dtype: object

### Q38. Access first N rows.
> 💡 **Hint:** `df.head(N)` — default N is 5.

---

In [400]:
df1.head(5)

  First_Name  Marks  Multiplier  Gender
0   Sanchita     90          10  Female
1       Bapu     80          10    Male
2      parag     50          10    Male

### Q39. Access last N rows.
> 💡 **Hint:** `df.tail(N)` — default N is 5.

---

In [401]:
df1.tail(1)

  First_Name  Marks  Multiplier Gender
2      parag     50          10   Male

### Q40. Extract random sample from DataFrame.
> 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.

---

In [402]:
df1.sample()

  First_Name  Marks  Multiplier Gender
1       Bapu     80          10   Male

## 🔹 Section 3: Data Cleaning (Q41–Q60)

---

### Q41. Detect missing values using `isnull()`.
> 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.

---

In [403]:
import pandas as pd
import numpy as np

raw_df = pd.DataFrame({
    'Emp_ID': [101,102,103,104,105,106,107,108,109,110,
               111,112,113,114,115,116,117,118,119,120,
               121,122,123,124,125,126,127,128,129,129],

    'Name': ['Bapu','Parag','Sanchita','Rohit','Virat',
             'Amit','Neha','Pooja','Kiran','Ravi',
             'Anita','Sunil','Meena','Ajay','Priya',
             'Vikas','Kajal','Nitin','Deepa','Raj',
             'Sneha','Arun','Komal','Mohan','Ritu',
             'Asha','Sachin','Dipak','Ramesh','Ramesh'],

    'Department': ['IT','HR','Finance','IT','HR',
                   'Finance','IT','HR',np.nan,'Finance',
                   'IT','HR','Finance','IT','HR',
                   'Finance','IT','HR','Finance','IT',
                   'HR','Finance','IT','HR','Finance',
                   'IT','HR','Finance','IT','IT'],

    'Salary': [50000,45000,60000,np.nan,55000,
               62000,48000,47000,51000,63000,
               52000,46000,np.nan,58000,54000,
               61000,49500,45500,60500,59000,
               47000,64000,53000,45000,62000,
               50000,48000,61000,57000,57000],

    'Joining_Date': ['2022-01-15','2021-06-20','2020-03-10','2022-08-01','2021-11-05',
                     '2019-12-12','2023-02-18','2020-07-07','2021-04-14','2018-09-09',
                     '2022-05-25','2021-10-10','2020-01-01','2019-03-15','2023-01-20',
                     '2022-02-11','2021-08-18','2020-06-30','2019-07-22','2022-09-05',
                     '2021-12-01','2020-10-10','2019-11-11','2023-03-03','2022-04-04',
                     '2021-05-05','2020-08-08','2019-09-09','2022-07-07','2022-07-07'],

    'Performance': ['Good','Excellent','Average','Good','Excellent',
                    'Average','Good','Excellent','Good','Average',
                    'Excellent','Good','Average','Good','Excellent',
                    'Average','Good','Excellent','Average','Good',
                    'Excellent','Average','Good','Excellent','Average',
                    'Good','Excellent','Average','Good','Good']
})

print(raw_df)

    Emp_ID      Name Department   Salary Joining_Date Performance
0      101      Bapu         IT  50000.0   2022-01-15        Good
1      102     Parag         HR  45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance  60000.0   2020-03-10     Average
3      104     Rohit         IT      NaN   2022-08-01        Good
4      105     Virat         HR  55000.0   2021-11-05   Excellent
5      106      Amit    Finance  62000.0   2019-12-12     Average
6      107      Neha         IT  48000.0   2023-02-18        Good
7      108     Pooja         HR  47000.0   2020-07-07   Excellent
8      109     Kiran        NaN  51000.0   2021-04-14        Good
9      110      Ravi    Finance  63000.0   2018-09-09     Average
10     111     Anita         IT  52000.0   2022-05-25   Excellent
11     112     Sunil         HR  46000.0   2021-10-10        Good
12     113     Meena    Finance      NaN   2020-01-01     Average
13     114      Ajay         IT  58000.0   2019-03-15        Good
14     115     Priya         HR  54000.0   2023-01-20   Excellent
15     116     Vikas    Finance  61000.0   2022-02-11     Average
16     117     Kajal         IT  49500.0   2021-08-18        Good
17     118     Nitin         HR  45500.0   2020-06-30   Excellent
18     119     Deepa    Finance  60500.0   2019-07-22     Average
19     120       Raj         IT  59000.0   2022-09-05        Good
20     121     Sneha         HR  47000.0   2021-12-01   Excellent
21     122      Arun    Finance  64000.0   2020-10-10     Average
22     123     Komal         IT  53000.0   2019-11-11        Good
23     124     Mohan         HR  45000.0   2023-03-03   Excellent
24     125      Ritu    Finance  62000.0   2022-04-04     Average
25     126      Asha         IT  50000.0   2021-05-05        Good
26     127    Sachin         HR  48000.0   2020-08-08   Excellent
27     128     Dipak    Finance  61000.0   2019-09-09     Average
28     129    Ramesh         IT  57000.0   2022-07-07        Good
29     129    Ramesh         IT  57000.0   2022-07-07        Good

In [404]:
print(raw_df.isnull().sum())
print()
print(raw_df.isnull().any())

Emp_ID          0
Name            0
Department      1
Salary          2
Joining_Date    0
Performance     0
dtype: int64

Emp_ID          False
Name            False
Department       True
Salary           True
Joining_Date    False
Performance     False
dtype: bool

### Q42. Drop missing values using `dropna()`.
> 💡 **Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.

---

In [405]:
raw_df.dropna(axis=1)

    Emp_ID      Name Joining_Date Performance
0      101      Bapu   2022-01-15        Good
1      102     Parag   2021-06-20   Excellent
2      103  Sanchita   2020-03-10     Average
3      104     Rohit   2022-08-01        Good
4      105     Virat   2021-11-05   Excellent
5      106      Amit   2019-12-12     Average
6      107      Neha   2023-02-18        Good
7      108     Pooja   2020-07-07   Excellent
8      109     Kiran   2021-04-14        Good
9      110      Ravi   2018-09-09     Average
10     111     Anita   2022-05-25   Excellent
11     112     Sunil   2021-10-10        Good
12     113     Meena   2020-01-01     Average
13     114      Ajay   2019-03-15        Good
14     115     Priya   2023-01-20   Excellent
15     116     Vikas   2022-02-11     Average
16     117     Kajal   2021-08-18        Good
17     118     Nitin   2020-06-30   Excellent
18     119     Deepa   2019-07-22     Average
19     120       Raj   2022-09-05        Good
20     121     Sneha   2021-12-01   Excellent
21     122      Arun   2020-10-10     Average
22     123     Komal   2019-11-11        Good
23     124     Mohan   2023-03-03   Excellent
24     125      Ritu   2022-04-04     Average
25     126      Asha   2021-05-05        Good
26     127    Sachin   2020-08-08   Excellent
27     128     Dipak   2019-09-09     Average
28     129    Ramesh   2022-07-07        Good
29     129    Ramesh   2022-07-07        Good

In [406]:
raw_df

    Emp_ID      Name Department   Salary Joining_Date Performance
0      101      Bapu         IT  50000.0   2022-01-15        Good
1      102     Parag         HR  45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance  60000.0   2020-03-10     Average
3      104     Rohit         IT      NaN   2022-08-01        Good
4      105     Virat         HR  55000.0   2021-11-05   Excellent
5      106      Amit    Finance  62000.0   2019-12-12     Average
6      107      Neha         IT  48000.0   2023-02-18        Good
7      108     Pooja         HR  47000.0   2020-07-07   Excellent
8      109     Kiran        NaN  51000.0   2021-04-14        Good
9      110      Ravi    Finance  63000.0   2018-09-09     Average
10     111     Anita         IT  52000.0   2022-05-25   Excellent
11     112     Sunil         HR  46000.0   2021-10-10        Good
12     113     Meena    Finance      NaN   2020-01-01     Average
13     114      Ajay         IT  58000.0   2019-03-15        Good
14     115     Priya         HR  54000.0   2023-01-20   Excellent
15     116     Vikas    Finance  61000.0   2022-02-11     Average
16     117     Kajal         IT  49500.0   2021-08-18        Good
17     118     Nitin         HR  45500.0   2020-06-30   Excellent
18     119     Deepa    Finance  60500.0   2019-07-22     Average
19     120       Raj         IT  59000.0   2022-09-05        Good
20     121     Sneha         HR  47000.0   2021-12-01   Excellent
21     122      Arun    Finance  64000.0   2020-10-10     Average
22     123     Komal         IT  53000.0   2019-11-11        Good
23     124     Mohan         HR  45000.0   2023-03-03   Excellent
24     125      Ritu    Finance  62000.0   2022-04-04     Average
25     126      Asha         IT  50000.0   2021-05-05        Good
26     127    Sachin         HR  48000.0   2020-08-08   Excellent
27     128     Dipak    Finance  61000.0   2019-09-09     Average
28     129    Ramesh         IT  57000.0   2022-07-07        Good
29     129    Ramesh         IT  57000.0   2022-07-07        Good

### Q43. Fill missing values with a constant.
> 💡 **Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`. You can also pass a dict to fill different columns with different values.

---

In [407]:
raw_df[['Salary','Department']].fillna({'Salary':0,'Department':'IT1'}) # for multiple column
# raw_df['Department'].fillna('IT')#for a single column
# raw_df['Salary'].fillna(0)

     Salary Department
0   50000.0         IT
1   45000.0         HR
2   60000.0    Finance
3       0.0         IT
4   55000.0         HR
5   62000.0    Finance
6   48000.0         IT
7   47000.0         HR
8   51000.0        IT1
9   63000.0    Finance
10  52000.0         IT
11  46000.0         HR
12      0.0    Finance
13  58000.0         IT
14  54000.0         HR
15  61000.0    Finance
16  49500.0         IT
17  45500.0         HR
18  60500.0    Finance
19  59000.0         IT
20  47000.0         HR
21  64000.0    Finance
22  53000.0         IT
23  45000.0         HR
24  62000.0    Finance
25  50000.0         IT
26  48000.0         HR
27  61000.0    Finance
28  57000.0         IT
29  57000.0         IT

In [408]:
raw_df

    Emp_ID      Name Department   Salary Joining_Date Performance
0      101      Bapu         IT  50000.0   2022-01-15        Good
1      102     Parag         HR  45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance  60000.0   2020-03-10     Average
3      104     Rohit         IT      NaN   2022-08-01        Good
4      105     Virat         HR  55000.0   2021-11-05   Excellent
5      106      Amit    Finance  62000.0   2019-12-12     Average
6      107      Neha         IT  48000.0   2023-02-18        Good
7      108     Pooja         HR  47000.0   2020-07-07   Excellent
8      109     Kiran        NaN  51000.0   2021-04-14        Good
9      110      Ravi    Finance  63000.0   2018-09-09     Average
10     111     Anita         IT  52000.0   2022-05-25   Excellent
11     112     Sunil         HR  46000.0   2021-10-10        Good
12     113     Meena    Finance      NaN   2020-01-01     Average
13     114      Ajay         IT  58000.0   2019-03-15        Good
14     115     Priya         HR  54000.0   2023-01-20   Excellent
15     116     Vikas    Finance  61000.0   2022-02-11     Average
16     117     Kajal         IT  49500.0   2021-08-18        Good
17     118     Nitin         HR  45500.0   2020-06-30   Excellent
18     119     Deepa    Finance  60500.0   2019-07-22     Average
19     120       Raj         IT  59000.0   2022-09-05        Good
20     121     Sneha         HR  47000.0   2021-12-01   Excellent
21     122      Arun    Finance  64000.0   2020-10-10     Average
22     123     Komal         IT  53000.0   2019-11-11        Good
23     124     Mohan         HR  45000.0   2023-03-03   Excellent
24     125      Ritu    Finance  62000.0   2022-04-04     Average
25     126      Asha         IT  50000.0   2021-05-05        Good
26     127    Sachin         HR  48000.0   2020-08-08   Excellent
27     128     Dipak    Finance  61000.0   2019-09-09     Average
28     129    Ramesh         IT  57000.0   2022-07-07        Good
29     129    Ramesh         IT  57000.0   2022-07-07        Good

### Q44. Fill missing values using mean/median.
> 💡 **Hint:** `df["col"].fillna(df["col"].mean())` or `df["col"].fillna(df["col"].median())`.

---

In [409]:
print(raw_df['Salary'].fillna(raw_df['Salary'].mean().round(3)))
print('\n===============filling nan with median=========\n')
raw_df['Salary'].fillna(raw_df['Salary'].median())

0     50000.000
1     45000.000
2     60000.000
3     53946.429
4     55000.000
5     62000.000
6     48000.000
7     47000.000
8     51000.000
9     63000.000
10    52000.000
11    46000.000
12    53946.429
13    58000.000
14    54000.000
15    61000.000
16    49500.000
17    45500.000
18    60500.000
19    59000.000
20    47000.000
21    64000.000
22    53000.000
23    45000.000
24    62000.000
25    50000.000
26    48000.000
27    61000.000
28    57000.000
29    57000.000
Name: Salary, dtype: float64

===============filling nan with median=========

0     50000.0
1     45000.0
2     60000.0
3     53500.0
4     55000.0
5     62000.0
6     48000.0
7     47000.0
8     51000.0
9     63000.0
10    52000.0
11    46000.0
12    53500.0
13    58000.0
14    54000.0
15    61000.0
16    49500.0
17    45500.0
18    60500.0
19    59000.0
20    47000.0
21    64000.0
22    53000.0
23    45000.0
24    62000.0
25    50000.0
26    48000.0
27    61000.0
28    57000.0
29    57000.0
Name: Salary, dtype: float64

### Q45. Use forward fill and backward fill.
> 💡 **Hint:** `df.ffill()` propagates the last valid value forward. `df.bfill()` fills using the next valid value.

---

In [410]:
print(raw_df.ffill())

print(raw_df.bfill())

    Emp_ID      Name Department   Salary Joining_Date Performance
0      101      Bapu         IT  50000.0   2022-01-15        Good
1      102     Parag         HR  45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance  60000.0   2020-03-10     Average
3      104     Rohit         IT  60000.0   2022-08-01        Good
4      105     Virat         HR  55000.0   2021-11-05   Excellent
5      106      Amit    Finance  62000.0   2019-12-12     Average
6      107      Neha         IT  48000.0   2023-02-18        Good
7      108     Pooja         HR  47000.0   2020-07-07   Excellent
8      109     Kiran         HR  51000.0   2021-04-14        Good
9      110      Ravi    Finance  63000.0   2018-09-09     Average
10     111     Anita         IT  52000.0   2022-05-25   Excellent
11     112     Sunil         HR  46000.0   2021-10-10        Good
12     113     Meena    Finance  46000.0   2020-01-01     Average
13     114      Ajay         IT  58000.0   2019-03-15        Good
14     115     Priya         HR  54000.0   2023-01-20   Excellent
15     116     Vikas    Finance  61000.0   2022-02-11     Average
16     117     Kajal         IT  49500.0   2021-08-18        Good
17     118     Nitin         HR  45500.0   2020-06-30   Excellent
18     119     Deepa    Finance  60500.0   2019-07-22     Average
19     120       Raj         IT  59000.0   2022-09-05        Good
20     121     Sneha         HR  47000.0   2021-12-01   Excellent
21     122      Arun    Finance  64000.0   2020-10-10     Average
22     123     Komal         IT  53000.0   2019-11-11        Good
23     124     Mohan         HR  45000.0   2023-03-03   Excellent
24     125      Ritu    Finance  62000.0   2022-04-04     Average
25     126      Asha         IT  50000.0   2021-05-05        Good
26     127    Sachin         HR  48000.0   2020-08-08   Excellent
27     128     Dipak    Finance  61000.0   2019-09-09     Average
28     129    Ramesh         IT  57000.0   2022-07-07        Good
29     129    Ramesh         IT  57000.0   2022-07-07        Good
    Emp_ID      Name Department   Salary Joining_Date Performance
0      101      Bapu         IT  50000.0   2022-01-15        Good
1      102     Parag         HR  45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance  60000.0   2020-03-10     Average
3      104     Rohit         IT  55000.0   2022-08-01        Good
4      105     Virat         HR  55000.0   2021-11-05   Excellent
5      106      Amit    Finance  62000.0   2019-12-12     Average
6      107      Neha         IT  48000.0   2023-02-18        Good
7      108     Pooja         HR  47000.0   2020-07-07   Excellent
8      109     Kiran    Finance  51000.0   2021-04-14        Good
9      110      Ravi    Finance  63000.0   2018-09-09     Average
10     111     Anita         IT  52000.0   2022-05-25   Excellent
11     112     Sunil         HR  46000.0   2021-10-10        Good
12     113     Meena    Finance  58000.0   2020-01-01     Average
13     114      Ajay         IT  58000.0   2019-03-15        Good
14     115     Priya         HR  54000.0   2023-01-20   Excellent
15     116     Vikas    Finance  61000.0   2022-02-11     Average
16     117     Kajal         IT  49500.0   2021-08-18        Good
17     118     Nitin         HR  45500.0   2020-06-30   Excellent
18     119     Deepa    Finance  60500.0   2019-07-22     Average
19     120       Raj         IT  59000.0   2022-09-05        Good
20     121     Sneha         HR  47000.0   2021-12-01   Excellent
21     122      Arun    Finance  64000.0   2020-10-10     Average
22     123     Komal         IT  53000.0   2019-11-11        Good
23     124     Mohan         HR  45000.0   2023-03-03   Excellent
24     125      Ritu    Finance  62000.0   2022-04-04     Average
25     126      Asha         IT  50000.0   2021-05-05        Good
26     127    Sachin         HR  48000.0   2020-08-08   Excellent
27     128     Dipak    Finance  61000.0   2019-09-09     Average
28     129    Ramesh         IT  57000.0   2022-07-07        Good
29     129    Ramesh         IT  57000.0   2022-07-07        Good

### Q46. Convert data type using `astype()`.
> 💡 **Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`. Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.

---

In [411]:
print(raw_df['Salary'].astype('Int32'))
print(raw_df['Department'].astype('category'))
pd.to_numeric(raw_df['Department'], errors='coerce')

0     50000
1     45000
2     60000
3      <NA>
4     55000
5     62000
6     48000
7     47000
8     51000
9     63000
10    52000
11    46000
12     <NA>
13    58000
14    54000
15    61000
16    49500
17    45500
18    60500
19    59000
20    47000
21    64000
22    53000
23    45000
24    62000
25    50000
26    48000
27    61000
28    57000
29    57000
Name: Salary, dtype: Int32
0          IT
1          HR
2     Finance
3          IT
4          HR
5     Finance
6          IT
7          HR
8         NaN
9     Finance
10         IT
11         HR
12    Finance
13         IT
14         HR
15    Finance
16         IT
17         HR
18    Finance
19         IT
20         HR
21    Finance
22         IT
23         HR
24    Finance
25         IT
26         HR
27    Finance
28         IT
29         IT
Name: Department, dtype: category
Categories (3, str): ['Finance', 'HR', 'IT']

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
22   NaN
23   NaN
24   NaN
25   NaN
26   NaN
27   NaN
28   NaN
29   NaN
Name: Department, dtype: float64

### Q47. Clean string column using `.str.lower()`.
> 💡 **Hint:** Access the `.str` accessor first: `df["col"].str.lower()`. Similarly `.str.upper()`, `.str.title()`.

---

In [412]:
raw_df['Name'].str.lower()
raw_df['Name'].str.upper()
raw_df['Name'].str.title()
raw_df['Performance'].str.upper()

0          GOOD
1     EXCELLENT
2       AVERAGE
3          GOOD
4     EXCELLENT
5       AVERAGE
6          GOOD
7     EXCELLENT
8          GOOD
9       AVERAGE
10    EXCELLENT
11         GOOD
12      AVERAGE
13         GOOD
14    EXCELLENT
15      AVERAGE
16         GOOD
17    EXCELLENT
18      AVERAGE
19         GOOD
20    EXCELLENT
21      AVERAGE
22         GOOD
23    EXCELLENT
24      AVERAGE
25         GOOD
26    EXCELLENT
27      AVERAGE
28         GOOD
29         GOOD
Name: Performance, dtype: str

### Q48. Trim whitespace in strings.
> 💡 **Hint:** `df["col"].str.strip()` removes leading and trailing spaces. Use `.str.lstrip()` / `.str.rstrip()` for one side.

---

In [413]:
raw_df['Name'].str.strip()
raw_df['Name'].str.lstrip()
raw_df['Name'].str.rstrip()

0         Bapu
1        Parag
2     Sanchita
3        Rohit
4        Virat
5         Amit
6         Neha
7        Pooja
8        Kiran
9         Ravi
10       Anita
11       Sunil
12       Meena
13        Ajay
14       Priya
15       Vikas
16       Kajal
17       Nitin
18       Deepa
19         Raj
20       Sneha
21        Arun
22       Komal
23       Mohan
24        Ritu
25        Asha
26      Sachin
27       Dipak
28      Ramesh
29      Ramesh
Name: Name, dtype: str

### Q49. Replace substring in column.
> 💡 **Hint:** `df["col"].str.replace("old", "new")`. Add `regex=True` for pattern-based replacement.

---

In [414]:
raw_df['Name'].str.replace('Parag','Dhomane')

0         Bapu
1      Dhomane
2     Sanchita
3        Rohit
4        Virat
5         Amit
6         Neha
7        Pooja
8        Kiran
9         Ravi
10       Anita
11       Sunil
12       Meena
13        Ajay
14       Priya
15       Vikas
16       Kajal
17       Nitin
18       Deepa
19         Raj
20       Sneha
21        Arun
22       Komal
23       Mohan
24        Ritu
25        Asha
26      Sachin
27       Dipak
28      Ramesh
29      Ramesh
Name: Name, dtype: str

### Q50. Extract part of string using `.str`.
> 💡 **Hint:** `df["col"].str[:3]` for first 3 chars. Use `.str.split("@").str[1]` to extract after a delimiter.

---

In [415]:
raw_df['Name'].str[:4]
raw_df['Name'].str.split().str[0]

0         Bapu
1        Parag
2     Sanchita
3        Rohit
4        Virat
5         Amit
6         Neha
7        Pooja
8        Kiran
9         Ravi
10       Anita
11       Sunil
12       Meena
13        Ajay
14       Priya
15       Vikas
16       Kajal
17       Nitin
18       Deepa
19         Raj
20       Sneha
21        Arun
22       Komal
23       Mohan
24        Ritu
25        Asha
26      Sachin
27       Dipak
28      Ramesh
29      Ramesh
Name: Name, dtype: object

### Q51. Detect duplicate rows.
> 💡 **Hint:** `df.duplicated()` returns a boolean Series. Use `df[df.duplicated()]` to see the actual duplicate rows.

---

In [416]:
raw_df.duplicated()
raw_df[raw_df.duplicated()]

    Emp_ID    Name Department   Salary Joining_Date Performance
29     129  Ramesh         IT  57000.0   2022-07-07        Good

### Q52. Remove duplicates using `drop_duplicates()`.
> 💡 **Hint:** `df.drop_duplicates()` keeps the first occurrence by default. Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.

---

In [417]:
raw_df.drop_duplicates()

    Emp_ID      Name Department   Salary Joining_Date Performance
0      101      Bapu         IT  50000.0   2022-01-15        Good
1      102     Parag         HR  45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance  60000.0   2020-03-10     Average
3      104     Rohit         IT      NaN   2022-08-01        Good
4      105     Virat         HR  55000.0   2021-11-05   Excellent
5      106      Amit    Finance  62000.0   2019-12-12     Average
6      107      Neha         IT  48000.0   2023-02-18        Good
7      108     Pooja         HR  47000.0   2020-07-07   Excellent
8      109     Kiran        NaN  51000.0   2021-04-14        Good
9      110      Ravi    Finance  63000.0   2018-09-09     Average
10     111     Anita         IT  52000.0   2022-05-25   Excellent
11     112     Sunil         HR  46000.0   2021-10-10        Good
12     113     Meena    Finance      NaN   2020-01-01     Average
13     114      Ajay         IT  58000.0   2019-03-15        Good
14     115     Priya         HR  54000.0   2023-01-20   Excellent
15     116     Vikas    Finance  61000.0   2022-02-11     Average
16     117     Kajal         IT  49500.0   2021-08-18        Good
17     118     Nitin         HR  45500.0   2020-06-30   Excellent
18     119     Deepa    Finance  60500.0   2019-07-22     Average
19     120       Raj         IT  59000.0   2022-09-05        Good
20     121     Sneha         HR  47000.0   2021-12-01   Excellent
21     122      Arun    Finance  64000.0   2020-10-10     Average
22     123     Komal         IT  53000.0   2019-11-11        Good
23     124     Mohan         HR  45000.0   2023-03-03   Excellent
24     125      Ritu    Finance  62000.0   2022-04-04     Average
25     126      Asha         IT  50000.0   2021-05-05        Good
26     127    Sachin         HR  48000.0   2020-08-08   Excellent
27     128     Dipak    Finance  61000.0   2019-09-09     Average
28     129    Ramesh         IT  57000.0   2022-07-07        Good

### Q53. Rename row labels.
> 💡 **Hint:** `df.rename(index={old_label: new_label})`.

---

In [418]:
raw_df.reset_index()

    index  Emp_ID      Name Department   Salary Joining_Date Performance
0       0     101      Bapu         IT  50000.0   2022-01-15        Good
1       1     102     Parag         HR  45000.0   2021-06-20   Excellent
2       2     103  Sanchita    Finance  60000.0   2020-03-10     Average
3       3     104     Rohit         IT      NaN   2022-08-01        Good
4       4     105     Virat         HR  55000.0   2021-11-05   Excellent
5       5     106      Amit    Finance  62000.0   2019-12-12     Average
6       6     107      Neha         IT  48000.0   2023-02-18        Good
7       7     108     Pooja         HR  47000.0   2020-07-07   Excellent
8       8     109     Kiran        NaN  51000.0   2021-04-14        Good
9       9     110      Ravi    Finance  63000.0   2018-09-09     Average
10     10     111     Anita         IT  52000.0   2022-05-25   Excellent
11     11     112     Sunil         HR  46000.0   2021-10-10        Good
12     12     113     Meena    Finance      NaN   2020-01-01     Average
13     13     114      Ajay         IT  58000.0   2019-03-15        Good
14     14     115     Priya         HR  54000.0   2023-01-20   Excellent
15     15     116     Vikas    Finance  61000.0   2022-02-11     Average
16     16     117     Kajal         IT  49500.0   2021-08-18        Good
17     17     118     Nitin         HR  45500.0   2020-06-30   Excellent
18     18     119     Deepa    Finance  60500.0   2019-07-22     Average
19     19     120       Raj         IT  59000.0   2022-09-05        Good
20     20     121     Sneha         HR  47000.0   2021-12-01   Excellent
21     21     122      Arun    Finance  64000.0   2020-10-10     Average
22     22     123     Komal         IT  53000.0   2019-11-11        Good
23     23     124     Mohan         HR  45000.0   2023-03-03   Excellent
24     24     125      Ritu    Finance  62000.0   2022-04-04     Average
25     25     126      Asha         IT  50000.0   2021-05-05        Good
26     26     127    Sachin         HR  48000.0   2020-08-08   Excellent
27     27     128     Dipak    Finance  61000.0   2019-09-09     Average
28     28     129    Ramesh         IT  57000.0   2022-07-07        Good
29     29     129    Ramesh         IT  57000.0   2022-07-07        Good

In [419]:
# raw_df.set_index('Emp_ID',inplace=True)
raw_df.rename(index={101:'E1',102:'E2',103:'E3'},inplace=True)
raw_df

    Emp_ID      Name Department   Salary Joining_Date Performance
0      101      Bapu         IT  50000.0   2022-01-15        Good
1      102     Parag         HR  45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance  60000.0   2020-03-10     Average
3      104     Rohit         IT      NaN   2022-08-01        Good
4      105     Virat         HR  55000.0   2021-11-05   Excellent
5      106      Amit    Finance  62000.0   2019-12-12     Average
6      107      Neha         IT  48000.0   2023-02-18        Good
7      108     Pooja         HR  47000.0   2020-07-07   Excellent
8      109     Kiran        NaN  51000.0   2021-04-14        Good
9      110      Ravi    Finance  63000.0   2018-09-09     Average
10     111     Anita         IT  52000.0   2022-05-25   Excellent
11     112     Sunil         HR  46000.0   2021-10-10        Good
12     113     Meena    Finance      NaN   2020-01-01     Average
13     114      Ajay         IT  58000.0   2019-03-15        Good
14     115     Priya         HR  54000.0   2023-01-20   Excellent
15     116     Vikas    Finance  61000.0   2022-02-11     Average
16     117     Kajal         IT  49500.0   2021-08-18        Good
17     118     Nitin         HR  45500.0   2020-06-30   Excellent
18     119     Deepa    Finance  60500.0   2019-07-22     Average
19     120       Raj         IT  59000.0   2022-09-05        Good
20     121     Sneha         HR  47000.0   2021-12-01   Excellent
21     122      Arun    Finance  64000.0   2020-10-10     Average
22     123     Komal         IT  53000.0   2019-11-11        Good
23     124     Mohan         HR  45000.0   2023-03-03   Excellent
24     125      Ritu    Finance  62000.0   2022-04-04     Average
25     126      Asha         IT  50000.0   2021-05-05        Good
26     127    Sachin         HR  48000.0   2020-08-08   Excellent
27     128     Dipak    Finance  61000.0   2019-09-09     Average
28     129    Ramesh         IT  57000.0   2022-07-07        Good
29     129    Ramesh         IT  57000.0   2022-07-07        Good

### Q54. Handle inconsistent data.
> 💡 **Hint:** Use `.str.strip().str.lower()` to normalize strings. Use `.replace({...})` to map inconsistent values to a standard form.

---

In [420]:
# raw_df.drop(columns=[(0, 0)], inplace=True)


raw_df['Emp_ID'] = raw_df['Emp_ID'].replace({
    'E1': 101,
    'E2': 102,
    'E3': 103
})
raw_df

    Emp_ID      Name Department   Salary Joining_Date Performance
0      101      Bapu         IT  50000.0   2022-01-15        Good
1      102     Parag         HR  45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance  60000.0   2020-03-10     Average
3      104     Rohit         IT      NaN   2022-08-01        Good
4      105     Virat         HR  55000.0   2021-11-05   Excellent
5      106      Amit    Finance  62000.0   2019-12-12     Average
6      107      Neha         IT  48000.0   2023-02-18        Good
7      108     Pooja         HR  47000.0   2020-07-07   Excellent
8      109     Kiran        NaN  51000.0   2021-04-14        Good
9      110      Ravi    Finance  63000.0   2018-09-09     Average
10     111     Anita         IT  52000.0   2022-05-25   Excellent
11     112     Sunil         HR  46000.0   2021-10-10        Good
12     113     Meena    Finance      NaN   2020-01-01     Average
13     114      Ajay         IT  58000.0   2019-03-15        Good
14     115     Priya         HR  54000.0   2023-01-20   Excellent
15     116     Vikas    Finance  61000.0   2022-02-11     Average
16     117     Kajal         IT  49500.0   2021-08-18        Good
17     118     Nitin         HR  45500.0   2020-06-30   Excellent
18     119     Deepa    Finance  60500.0   2019-07-22     Average
19     120       Raj         IT  59000.0   2022-09-05        Good
20     121     Sneha         HR  47000.0   2021-12-01   Excellent
21     122      Arun    Finance  64000.0   2020-10-10     Average
22     123     Komal         IT  53000.0   2019-11-11        Good
23     124     Mohan         HR  45000.0   2023-03-03   Excellent
24     125      Ritu    Finance  62000.0   2022-04-04     Average
25     126      Asha         IT  50000.0   2021-05-05        Good
26     127    Sachin         HR  48000.0   2020-08-08   Excellent
27     128     Dipak    Finance  61000.0   2019-09-09     Average
28     129    Ramesh         IT  57000.0   2022-07-07        Good
29     129    Ramesh         IT  57000.0   2022-07-07        Good

### Q55. Replace values in DataFrame.
> 💡 **Hint:** `df.replace("old", "new")` works DataFrame-wide. Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.

---

In [421]:
raw_df.replace('IT','it1')

    Emp_ID      Name Department   Salary Joining_Date Performance
0      101      Bapu        it1  50000.0   2022-01-15        Good
1      102     Parag         HR  45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance  60000.0   2020-03-10     Average
3      104     Rohit        it1      NaN   2022-08-01        Good
4      105     Virat         HR  55000.0   2021-11-05   Excellent
5      106      Amit    Finance  62000.0   2019-12-12     Average
6      107      Neha        it1  48000.0   2023-02-18        Good
7      108     Pooja         HR  47000.0   2020-07-07   Excellent
8      109     Kiran        NaN  51000.0   2021-04-14        Good
9      110      Ravi    Finance  63000.0   2018-09-09     Average
10     111     Anita        it1  52000.0   2022-05-25   Excellent
11     112     Sunil         HR  46000.0   2021-10-10        Good
12     113     Meena    Finance      NaN   2020-01-01     Average
13     114      Ajay        it1  58000.0   2019-03-15        Good
14     115     Priya         HR  54000.0   2023-01-20   Excellent
15     116     Vikas    Finance  61000.0   2022-02-11     Average
16     117     Kajal        it1  49500.0   2021-08-18        Good
17     118     Nitin         HR  45500.0   2020-06-30   Excellent
18     119     Deepa    Finance  60500.0   2019-07-22     Average
19     120       Raj        it1  59000.0   2022-09-05        Good
20     121     Sneha         HR  47000.0   2021-12-01   Excellent
21     122      Arun    Finance  64000.0   2020-10-10     Average
22     123     Komal        it1  53000.0   2019-11-11        Good
23     124     Mohan         HR  45000.0   2023-03-03   Excellent
24     125      Ritu    Finance  62000.0   2022-04-04     Average
25     126      Asha        it1  50000.0   2021-05-05        Good
26     127    Sachin         HR  48000.0   2020-08-08   Excellent
27     128     Dipak    Finance  61000.0   2019-09-09     Average
28     129    Ramesh        it1  57000.0   2022-07-07        Good
29     129    Ramesh        it1  57000.0   2022-07-07        Good

### Q56. Detect outliers in a column.
> 💡 **Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1. Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. Alternatively use Z-score: `|z| > 3`.


---

In [422]:
raw_df['Salary']=raw_df['Salary'].fillna(100000)
raw_df.iloc[8,2]=None
raw_df

    Emp_ID      Name Department    Salary Joining_Date Performance
0      101      Bapu         IT   50000.0   2022-01-15        Good
1      102     Parag         HR   45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance   60000.0   2020-03-10     Average
3      104     Rohit         IT  100000.0   2022-08-01        Good
4      105     Virat         HR   55000.0   2021-11-05   Excellent
5      106      Amit    Finance   62000.0   2019-12-12     Average
6      107      Neha         IT   48000.0   2023-02-18        Good
7      108     Pooja         HR   47000.0   2020-07-07   Excellent
8      109     Kiran        NaN   51000.0   2021-04-14        Good
9      110      Ravi    Finance   63000.0   2018-09-09     Average
10     111     Anita         IT   52000.0   2022-05-25   Excellent
11     112     Sunil         HR   46000.0   2021-10-10        Good
12     113     Meena    Finance  100000.0   2020-01-01     Average
13     114      Ajay         IT   58000.0   2019-03-15        Good
14     115     Priya         HR   54000.0   2023-01-20   Excellent
15     116     Vikas    Finance   61000.0   2022-02-11     Average
16     117     Kajal         IT   49500.0   2021-08-18        Good
17     118     Nitin         HR   45500.0   2020-06-30   Excellent
18     119     Deepa    Finance   60500.0   2019-07-22     Average
19     120       Raj         IT   59000.0   2022-09-05        Good
20     121     Sneha         HR   47000.0   2021-12-01   Excellent
21     122      Arun    Finance   64000.0   2020-10-10     Average
22     123     Komal         IT   53000.0   2019-11-11        Good
23     124     Mohan         HR   45000.0   2023-03-03   Excellent
24     125      Ritu    Finance   62000.0   2022-04-04     Average
25     126      Asha         IT   50000.0   2021-05-05        Good
26     127    Sachin         HR   48000.0   2020-08-08   Excellent
27     128     Dipak    Finance   61000.0   2019-09-09     Average
28     129    Ramesh         IT   57000.0   2022-07-07        Good
29     129    Ramesh         IT   57000.0   2022-07-07        Good

In [423]:
# Z-score
mean=raw_df['Salary'].mean()
print(mean)
std = raw_df['Salary'].std()
print(std)

z_score = (raw_df['Salary']-mean)/std
print(z_score >3)
print(z_score)

57016.666666666664
13181.415426412981
0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: Salary, dtype: bool
0    -0.532315
1    -0.911637
2     0.226329
3     3.260904
4    -0.152993
5     0.378058
6    -0.684044
7    -0.759908
8    -0.456451
9     0.453922
10   -0.380586
11   -0.835773
12    3.260904
13    0.074600
14   -0.228858
15    0.302193
16   -0.570247
17   -0.873705
18    0.264261
19    0.150464
20   -0.759908
21    0.529786
22   -0.304722
23   -0.911637
24    0.378058
25   -0.532315
26   -0.684044
27    0.302193
28   -0.001264
29   -0.001264
Name: Salary, dtype: float64

In [424]:
Q1=raw_df['Salary'].quantile(.25)
print(Q1)
Q2=raw_df['Salary'].quantile(0.50)
print(Q2)
Q3=raw_df['Salary'].quantile(0.75)
print(Q3)
IQR=Q3-Q1
print(IQR)
outlier_lower = Q1 - 1.5*IQR
print(outlier_lower)
outlier_upper = Q3 + 1.5*IQR
print(outlier_upper)

48375.0
54500.0
60875.0
12500.0
29625.0
79625.0

### Q57. Handle outliers using clipping.
> 💡 **Hint:** `df["col"].clip(lower=lo, upper=hi)` replaces values outside the bounds with the boundary values.

---

In [425]:
print(raw_df.fillna(0))
raw_df['Salary'].clip(outlier_lower,outlier_upper)

    Emp_ID      Name Department    Salary Joining_Date Performance
0      101      Bapu         IT   50000.0   2022-01-15        Good
1      102     Parag         HR   45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance   60000.0   2020-03-10     Average
3      104     Rohit         IT  100000.0   2022-08-01        Good
4      105     Virat         HR   55000.0   2021-11-05   Excellent
5      106      Amit    Finance   62000.0   2019-12-12     Average
6      107      Neha         IT   48000.0   2023-02-18        Good
7      108     Pooja         HR   47000.0   2020-07-07   Excellent
8      109     Kiran          0   51000.0   2021-04-14        Good
9      110      Ravi    Finance   63000.0   2018-09-09     Average
10     111     Anita         IT   52000.0   2022-05-25   Excellent
11     112     Sunil         HR   46000.0   2021-10-10        Good
12     113     Meena    Finance  100000.0   2020-01-01     Average
13     114      Ajay         IT   58000.0   2019-03-15        Good
14     115     Priya         HR   54000.0   2023-01-20   Excellent
15     116     Vikas    Finance   61000.0   2022-02-11     Average
16     117     Kajal         IT   49500.0   2021-08-18        Good
17     118     Nitin         HR   45500.0   2020-06-30   Excellent
18     119     Deepa    Finance   60500.0   2019-07-22     Average
19     120       Raj         IT   59000.0   2022-09-05        Good
20     121     Sneha         HR   47000.0   2021-12-01   Excellent
21     122      Arun    Finance   64000.0   2020-10-10     Average
22     123     Komal         IT   53000.0   2019-11-11        Good
23     124     Mohan         HR   45000.0   2023-03-03   Excellent
24     125      Ritu    Finance   62000.0   2022-04-04     Average
25     126      Asha         IT   50000.0   2021-05-05        Good
26     127    Sachin         HR   48000.0   2020-08-08   Excellent
27     128     Dipak    Finance   61000.0   2019-09-09     Average
28     129    Ramesh         IT   57000.0   2022-07-07        Good
29     129    Ramesh         IT   57000.0   2022-07-07        Good

0     50000.0
1     45000.0
2     60000.0
3     79625.0
4     55000.0
5     62000.0
6     48000.0
7     47000.0
8     51000.0
9     63000.0
10    52000.0
11    46000.0
12    79625.0
13    58000.0
14    54000.0
15    61000.0
16    49500.0
17    45500.0
18    60500.0
19    59000.0
20    47000.0
21    64000.0
22    53000.0
23    45000.0
24    62000.0
25    50000.0
26    48000.0
27    61000.0
28    57000.0
29    57000.0
Name: Salary, dtype: float64

### Q58. Standardize column names.
> 💡 **Hint:** `df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")` — clean all column names in one line.

---

In [426]:
raw_df.columns = raw_df.columns.str.strip().str.lower().str.replace(' ',"_")
raw_df

    emp_id      name department    salary joining_date performance
0      101      Bapu         IT   50000.0   2022-01-15        Good
1      102     Parag         HR   45000.0   2021-06-20   Excellent
2      103  Sanchita    Finance   60000.0   2020-03-10     Average
3      104     Rohit         IT  100000.0   2022-08-01        Good
4      105     Virat         HR   55000.0   2021-11-05   Excellent
5      106      Amit    Finance   62000.0   2019-12-12     Average
6      107      Neha         IT   48000.0   2023-02-18        Good
7      108     Pooja         HR   47000.0   2020-07-07   Excellent
8      109     Kiran        NaN   51000.0   2021-04-14        Good
9      110      Ravi    Finance   63000.0   2018-09-09     Average
10     111     Anita         IT   52000.0   2022-05-25   Excellent
11     112     Sunil         HR   46000.0   2021-10-10        Good
12     113     Meena    Finance  100000.0   2020-01-01     Average
13     114      Ajay         IT   58000.0   2019-03-15        Good
14     115     Priya         HR   54000.0   2023-01-20   Excellent
15     116     Vikas    Finance   61000.0   2022-02-11     Average
16     117     Kajal         IT   49500.0   2021-08-18        Good
17     118     Nitin         HR   45500.0   2020-06-30   Excellent
18     119     Deepa    Finance   60500.0   2019-07-22     Average
19     120       Raj         IT   59000.0   2022-09-05        Good
20     121     Sneha         HR   47000.0   2021-12-01   Excellent
21     122      Arun    Finance   64000.0   2020-10-10     Average
22     123     Komal         IT   53000.0   2019-11-11        Good
23     124     Mohan         HR   45000.0   2023-03-03   Excellent
24     125      Ritu    Finance   62000.0   2022-04-04     Average
25     126      Asha         IT   50000.0   2021-05-05        Good
26     127    Sachin         HR   48000.0   2020-08-08   Excellent
27     128     Dipak    Finance   61000.0   2019-09-09     Average
28     129    Ramesh         IT   57000.0   2022-07-07        Good
29     129    Ramesh         IT   57000.0   2022-07-07        Good

In [427]:
import pandas as pd
import numpy as np

df_operation = pd.DataFrame({
    'Emp_ID': [101,102,'103A',104,105,'106B',107,108,109,'110X',
               111,112,113,'114Y',115,116,'117Z',118,119,120],

    'Name': ['Bapu@','Parag#','Sanchita!','Rohit$','Virat%',
             'Sachin^','Dipak&','Ramesh*','Asha(','Neha)',
             'Kiran_','Anil+','Pooja=','Sneha?',
             'Ajay/','Raj\\','Maya:','Tina;','Riya,','Amit.'],

    'Department': ['IT','HR','Finance','IT','Sales',
                   'HR','Finance','IT','Sales','HR',
                   'IT','Finance','Sales','HR',
                   'IT','Finance','Sales','HR','IT','Finance'],

    'Salary': [50000,'55000',60000,'invalid',65000,
               52000,'58000',57000,62000,'N/A',
               54000,61000,'error',59000,
               56000,63000,'unknown',60000,58000,64000],

    'Joining_Date': ['2022-01-15','2021-06-20','2020-03-10','2022-08-01',
                     '2021-12-05','2023-02-14','2019-09-09','2022-07-07',
                     '2020-11-11','2021-05-18',
                     '2022-03-22','2020-10-10','2023-01-01','2021-04-12',
                     '2022-09-15','2020-08-20','2021-11-11','2022-06-06',
                     '2020-02-29','2023-03-03'],

    'Performance': ['Good','Excellent','Average','Good','Excellent',
                    'Average','Excellent','Good','Average','Excellent',
                    'Good','Average','Excellent','Good',
                    'Average','Excellent','Good','Average',
                    'Excellent','Good']
})

print(df_operation)

   Emp_ID       Name Department   Salary Joining_Date Performance
0     101      Bapu@         IT    50000   2022-01-15        Good
1     102     Parag#         HR    55000   2021-06-20   Excellent
2    103A  Sanchita!    Finance    60000   2020-03-10     Average
3     104     Rohit$         IT  invalid   2022-08-01        Good
4     105     Virat%      Sales    65000   2021-12-05   Excellent
5    106B    Sachin^         HR    52000   2023-02-14     Average
6     107     Dipak&    Finance    58000   2019-09-09   Excellent
7     108    Ramesh*         IT    57000   2022-07-07        Good
8     109      Asha(      Sales    62000   2020-11-11     Average
9    110X      Neha)         HR      N/A   2021-05-18   Excellent
10    111     Kiran_         IT    54000   2022-03-22        Good
11    112      Anil+    Finance    61000   2020-10-10     Average
12    113     Pooja=      Sales    error   2023-01-01   Excellent
13   114Y     Sneha?         HR    59000   2021-04-12        Good
14    115      Ajay/         IT    56000   2022-09-15     Average
15    116       Raj\    Finance    63000   2020-08-20   Excellent
16   117Z      Maya:      Sales  unknown   2021-11-11        Good
17    118      Tina;         HR    60000   2022-06-06     Average
18    119      Riya,         IT    58000   2020-02-29   Excellent
19    120      Amit.    Finance    64000   2023-03-03        Good

### Q59. Handle mixed data types in a column.
> 💡 **Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers, turning invalid strings into `NaN`.

---

In [428]:
df_operation['Salary']=pd.to_numeric(df_operation['Salary'],errors='coerce')
df_operation

   Emp_ID       Name Department   Salary Joining_Date Performance
0     101      Bapu@         IT  50000.0   2022-01-15        Good
1     102     Parag#         HR  55000.0   2021-06-20   Excellent
2    103A  Sanchita!    Finance  60000.0   2020-03-10     Average
3     104     Rohit$         IT      NaN   2022-08-01        Good
4     105     Virat%      Sales  65000.0   2021-12-05   Excellent
5    106B    Sachin^         HR  52000.0   2023-02-14     Average
6     107     Dipak&    Finance  58000.0   2019-09-09   Excellent
7     108    Ramesh*         IT  57000.0   2022-07-07        Good
8     109      Asha(      Sales  62000.0   2020-11-11     Average
9    110X      Neha)         HR      NaN   2021-05-18   Excellent
10    111     Kiran_         IT  54000.0   2022-03-22        Good
11    112      Anil+    Finance  61000.0   2020-10-10     Average
12    113     Pooja=      Sales      NaN   2023-01-01   Excellent
13   114Y     Sneha?         HR  59000.0   2021-04-12        Good
14    115      Ajay/         IT  56000.0   2022-09-15     Average
15    116       Raj\    Finance  63000.0   2020-08-20   Excellent
16   117Z      Maya:      Sales      NaN   2021-11-11        Good
17    118      Tina;         HR  60000.0   2022-06-06     Average
18    119      Riya,         IT  58000.0   2020-02-29   Excellent
19    120      Amit.    Finance  64000.0   2023-03-03        Good

### Q60. Remove special characters from text data.
> 💡 **Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)` — use regex to keep only alphanumeric characters.

---

In [429]:
# df_operation["Emp_ID"]=df_operation["Emp_ID"].str.replace(r"[^0-9]","",regex=True)
df_operation

   Emp_ID       Name Department   Salary Joining_Date Performance
0     101      Bapu@         IT  50000.0   2022-01-15        Good
1     102     Parag#         HR  55000.0   2021-06-20   Excellent
2    103A  Sanchita!    Finance  60000.0   2020-03-10     Average
3     104     Rohit$         IT      NaN   2022-08-01        Good
4     105     Virat%      Sales  65000.0   2021-12-05   Excellent
5    106B    Sachin^         HR  52000.0   2023-02-14     Average
6     107     Dipak&    Finance  58000.0   2019-09-09   Excellent
7     108    Ramesh*         IT  57000.0   2022-07-07        Good
8     109      Asha(      Sales  62000.0   2020-11-11     Average
9    110X      Neha)         HR      NaN   2021-05-18   Excellent
10    111     Kiran_         IT  54000.0   2022-03-22        Good
11    112      Anil+    Finance  61000.0   2020-10-10     Average
12    113     Pooja=      Sales      NaN   2023-01-01   Excellent
13   114Y     Sneha?         HR  59000.0   2021-04-12        Good
14    115      Ajay/         IT  56000.0   2022-09-15     Average
15    116       Raj\    Finance  63000.0   2020-08-20   Excellent
16   117Z      Maya:      Sales      NaN   2021-11-11        Good
17    118      Tina;         HR  60000.0   2022-06-06     Average
18    119      Riya,         IT  58000.0   2020-02-29   Excellent
19    120      Amit.    Finance  64000.0   2023-03-03        Good

In [430]:
df_operation['Name']= df_operation['Name'].str.replace(r"[^a-zA-Z0-9)]","",regex=True)
df_operation
df_operation['Emp_ID']=pd.Series(np.arange(100,120))
df_operation

    Emp_ID      Name Department   Salary Joining_Date Performance
0      100      Bapu         IT  50000.0   2022-01-15        Good
1      101     Parag         HR  55000.0   2021-06-20   Excellent
2      102  Sanchita    Finance  60000.0   2020-03-10     Average
3      103     Rohit         IT      NaN   2022-08-01        Good
4      104     Virat      Sales  65000.0   2021-12-05   Excellent
5      105    Sachin         HR  52000.0   2023-02-14     Average
6      106     Dipak    Finance  58000.0   2019-09-09   Excellent
7      107    Ramesh         IT  57000.0   2022-07-07        Good
8      108      Asha      Sales  62000.0   2020-11-11     Average
9      109     Neha)         HR      NaN   2021-05-18   Excellent
10     110     Kiran         IT  54000.0   2022-03-22        Good
11     111      Anil    Finance  61000.0   2020-10-10     Average
12     112     Pooja      Sales      NaN   2023-01-01   Excellent
13     113     Sneha         HR  59000.0   2021-04-12        Good
14     114      Ajay         IT  56000.0   2022-09-15     Average
15     115       Raj    Finance  63000.0   2020-08-20   Excellent
16     116      Maya      Sales      NaN   2021-11-11        Good
17     117      Tina         HR  60000.0   2022-06-06     Average
18     118      Riya         IT  58000.0   2020-02-29   Excellent
19     119      Amit    Finance  64000.0   2023-03-03        Good

## 🔹 Section 4: Data Manipulation (Q61–Q80)

---

### Q61. Filter rows using AND condition.
> 💡 **Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]` — wrap each condition in parentheses and use `&`.

---

In [431]:
df_operation[(df_operation['Salary']>60000) & (df_operation['Performance']=='Excellent')]

    Emp_ID   Name Department   Salary Joining_Date Performance
4      104  Virat      Sales  65000.0   2021-12-05   Excellent
15     115    Raj    Finance  63000.0   2020-08-20   Excellent

### Q62. Filter rows using OR condition.
> 💡 **Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]` — use `|` between conditions.

---

In [432]:
df_operation[(df_operation['Salary']>60000) | (df_operation['Performance']=='Excellent')]

    Emp_ID   Name Department   Salary Joining_Date Performance
1      101  Parag         HR  55000.0   2021-06-20   Excellent
4      104  Virat      Sales  65000.0   2021-12-05   Excellent
6      106  Dipak    Finance  58000.0   2019-09-09   Excellent
8      108   Asha      Sales  62000.0   2020-11-11     Average
9      109  Neha)         HR      NaN   2021-05-18   Excellent
11     111   Anil    Finance  61000.0   2020-10-10     Average
12     112  Pooja      Sales      NaN   2023-01-01   Excellent
15     115    Raj    Finance  63000.0   2020-08-20   Excellent
18     118   Riya         IT  58000.0   2020-02-29   Excellent
19     119   Amit    Finance  64000.0   2023-03-03        Good

### Q63. Filter rows using NOT condition.
> 💡 **Hint:** `df[~(df["col"] == "val")]` — use `~` to negate a boolean condition.

---

In [433]:
print(df_operation[~(df_operation["Salary"] < 60000)])

df_operation['Salary']=df_operation['Salary'].fillna(df_operation['Salary'].mean())
df_operation

    Emp_ID      Name Department   Salary Joining_Date Performance
2      102  Sanchita    Finance  60000.0   2020-03-10     Average
3      103     Rohit         IT      NaN   2022-08-01        Good
4      104     Virat      Sales  65000.0   2021-12-05   Excellent
8      108      Asha      Sales  62000.0   2020-11-11     Average
9      109     Neha)         HR      NaN   2021-05-18   Excellent
11     111      Anil    Finance  61000.0   2020-10-10     Average
12     112     Pooja      Sales      NaN   2023-01-01   Excellent
15     115       Raj    Finance  63000.0   2020-08-20   Excellent
16     116      Maya      Sales      NaN   2021-11-11        Good
17     117      Tina         HR  60000.0   2022-06-06     Average
19     119      Amit    Finance  64000.0   2023-03-03        Good

    Emp_ID      Name Department   Salary Joining_Date Performance
0      100      Bapu         IT  50000.0   2022-01-15        Good
1      101     Parag         HR  55000.0   2021-06-20   Excellent
2      102  Sanchita    Finance  60000.0   2020-03-10     Average
3      103     Rohit         IT  58375.0   2022-08-01        Good
4      104     Virat      Sales  65000.0   2021-12-05   Excellent
5      105    Sachin         HR  52000.0   2023-02-14     Average
6      106     Dipak    Finance  58000.0   2019-09-09   Excellent
7      107    Ramesh         IT  57000.0   2022-07-07        Good
8      108      Asha      Sales  62000.0   2020-11-11     Average
9      109     Neha)         HR  58375.0   2021-05-18   Excellent
10     110     Kiran         IT  54000.0   2022-03-22        Good
11     111      Anil    Finance  61000.0   2020-10-10     Average
12     112     Pooja      Sales  58375.0   2023-01-01   Excellent
13     113     Sneha         HR  59000.0   2021-04-12        Good
14     114      Ajay         IT  56000.0   2022-09-15     Average
15     115       Raj    Finance  63000.0   2020-08-20   Excellent
16     116      Maya      Sales  58375.0   2021-11-11        Good
17     117      Tina         HR  60000.0   2022-06-06     Average
18     118      Riya         IT  58000.0   2020-02-29   Excellent
19     119      Amit    Finance  64000.0   2023-03-03        Good

### Q64. Sort DataFrame by column values.
> 💡 **Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, `by=["col1","col2"]` for multi-column sort.

---

In [434]:
df_operation.sort_values(['Salary','Performance'],ascending=False)

    Emp_ID      Name Department   Salary Joining_Date Performance
4      104     Virat      Sales  65000.0   2021-12-05   Excellent
19     119      Amit    Finance  64000.0   2023-03-03        Good
15     115       Raj    Finance  63000.0   2020-08-20   Excellent
8      108      Asha      Sales  62000.0   2020-11-11     Average
11     111      Anil    Finance  61000.0   2020-10-10     Average
2      102  Sanchita    Finance  60000.0   2020-03-10     Average
17     117      Tina         HR  60000.0   2022-06-06     Average
13     113     Sneha         HR  59000.0   2021-04-12        Good
3      103     Rohit         IT  58375.0   2022-08-01        Good
16     116      Maya      Sales  58375.0   2021-11-11        Good
9      109     Neha)         HR  58375.0   2021-05-18   Excellent
12     112     Pooja      Sales  58375.0   2023-01-01   Excellent
6      106     Dipak    Finance  58000.0   2019-09-09   Excellent
18     118      Riya         IT  58000.0   2020-02-29   Excellent
7      107    Ramesh         IT  57000.0   2022-07-07        Good
14     114      Ajay         IT  56000.0   2022-09-15     Average
1      101     Parag         HR  55000.0   2021-06-20   Excellent
10     110     Kiran         IT  54000.0   2022-03-22        Good
5      105    Sachin         HR  52000.0   2023-02-14     Average
0      100      Bapu         IT  50000.0   2022-01-15        Good

In [435]:
df_operation.sort_values('Salary',ascending=False)

    Emp_ID      Name Department   Salary Joining_Date Performance
4      104     Virat      Sales  65000.0   2021-12-05   Excellent
19     119      Amit    Finance  64000.0   2023-03-03        Good
15     115       Raj    Finance  63000.0   2020-08-20   Excellent
8      108      Asha      Sales  62000.0   2020-11-11     Average
11     111      Anil    Finance  61000.0   2020-10-10     Average
17     117      Tina         HR  60000.0   2022-06-06     Average
2      102  Sanchita    Finance  60000.0   2020-03-10     Average
13     113     Sneha         HR  59000.0   2021-04-12        Good
16     116      Maya      Sales  58375.0   2021-11-11        Good
12     112     Pooja      Sales  58375.0   2023-01-01   Excellent
3      103     Rohit         IT  58375.0   2022-08-01        Good
9      109     Neha)         HR  58375.0   2021-05-18   Excellent
18     118      Riya         IT  58000.0   2020-02-29   Excellent
6      106     Dipak    Finance  58000.0   2019-09-09   Excellent
7      107    Ramesh         IT  57000.0   2022-07-07        Good
14     114      Ajay         IT  56000.0   2022-09-15     Average
1      101     Parag         HR  55000.0   2021-06-20   Excellent
10     110     Kiran         IT  54000.0   2022-03-22        Good
5      105    Sachin         HR  52000.0   2023-02-14     Average
0      100      Bapu         IT  50000.0   2022-01-15        Good

### Q65. Sort DataFrame by index.
> 💡 **Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.

---

In [436]:
df_sorting_index=df_operation.set_index('Emp_ID')
df_sorting_index

            Name Department   Salary Joining_Date Performance
Emp_ID
100         Bapu         IT  50000.0   2022-01-15        Good
101        Parag         HR  55000.0   2021-06-20   Excellent
102     Sanchita    Finance  60000.0   2020-03-10     Average
103        Rohit         IT  58375.0   2022-08-01        Good
104        Virat      Sales  65000.0   2021-12-05   Excellent
105       Sachin         HR  52000.0   2023-02-14     Average
106        Dipak    Finance  58000.0   2019-09-09   Excellent
107       Ramesh         IT  57000.0   2022-07-07        Good
108         Asha      Sales  62000.0   2020-11-11     Average
109        Neha)         HR  58375.0   2021-05-18   Excellent
110        Kiran         IT  54000.0   2022-03-22        Good
111         Anil    Finance  61000.0   2020-10-10     Average
112        Pooja      Sales  58375.0   2023-01-01   Excellent
113        Sneha         HR  59000.0   2021-04-12        Good
114         Ajay         IT  56000.0   2022-09-15     Average
115          Raj    Finance  63000.0   2020-08-20   Excellent
116         Maya      Sales  58375.0   2021-11-11        Good
117         Tina         HR  60000.0   2022-06-06     Average
118         Riya         IT  58000.0   2020-02-29   Excellent
119         Amit    Finance  64000.0   2023-03-03        Good

In [437]:
print(df_sorting_index['Salary'].dtype)

float64

In [438]:
# Salary column contain invalid, Error and nan values converted to nan using pd.numeric function 
df_sorting_index['Salary'] = pd.to_numeric(
    df_sorting_index['Salary'],
    errors='coerce'
)

In [439]:
df_sorting_index.sort_index(axis=1,ascending=True)

       Department Joining_Date      Name Performance   Salary
Emp_ID
100            IT   2022-01-15      Bapu        Good  50000.0
101            HR   2021-06-20     Parag   Excellent  55000.0
102       Finance   2020-03-10  Sanchita     Average  60000.0
103            IT   2022-08-01     Rohit        Good  58375.0
104         Sales   2021-12-05     Virat   Excellent  65000.0
105            HR   2023-02-14    Sachin     Average  52000.0
106       Finance   2019-09-09     Dipak   Excellent  58000.0
107            IT   2022-07-07    Ramesh        Good  57000.0
108         Sales   2020-11-11      Asha     Average  62000.0
109            HR   2021-05-18     Neha)   Excellent  58375.0
110            IT   2022-03-22     Kiran        Good  54000.0
111       Finance   2020-10-10      Anil     Average  61000.0
112         Sales   2023-01-01     Pooja   Excellent  58375.0
113            HR   2021-04-12     Sneha        Good  59000.0
114            IT   2022-09-15      Ajay     Average  56000.0
115       Finance   2020-08-20       Raj   Excellent  63000.0
116         Sales   2021-11-11      Maya        Good  58375.0
117            HR   2022-06-06      Tina     Average  60000.0
118            IT   2020-02-29      Riya   Excellent  58000.0
119       Finance   2023-03-03      Amit        Good  64000.0

### Q66. Add calculated column.
> 💡 **Hint:** `df["new"] = df["col1"] * df["col2"]` or use `.assign(new=lambda x: ...)` for chainable operations.

---

In [440]:
# dataframes salary column contain nan values that filled with 0
df_sorting_index['Bonus'] = 2000
df_sorting_index['Salary'] = (
    df_sorting_index['Salary']
    .fillna(0)
    .astype('int32')
)

In [441]:
df_sorting_index['Total_salary'] = df_sorting_index['Salary'] + df_sorting_index['Bonus']
df_sorting_index

,Name,Department,Salary,Joining_Date,Performance,Bonus,Total_salary
Emp_ID,,,,,,,
100,Bapu,IT,50000,2022-01-15,Good,2000,52000
101,Parag,HR,55000,2021-06-20,Excellent,2000,57000
102,Sanchita,Finance,60000,2020-03-10,Average,2000,62000
103,Rohit,IT,58375,2022-08-01,Good,2000,60375
104,Virat,Sales,65000,2021-12-05,Excellent,2000,67000
105,Sachin,HR,52000,2023-02-14,Average,2000,54000
106,Dipak,Finance,58000,2019-09-09,Excellent,2000,60000
107,Ramesh,IT,57000,2022-07-07,Good,2000,59000
108,Asha,Sales,62000,2020-11-11,Average,2000,64000
109,Neha),HR,58375,2021-05-18,Excellent,2000,60375
110,Kiran,IT,54000,2022-03-22,Good,2000,56000
111,Anil,Finance,61000,2020-10-10,Average,2000,63000
112,Pooja,Sales,58375,2023-01-01,Excellent,2000,60375
113,Sneha,HR,59000,2021-04-12,Good,2000,61000
114,Ajay,IT,56000,2022-09-15,Average,2000,58000
115,Raj,Finance,63000,2020-08-20,Excellent,2000,65000
116,Maya,Sales,58375,2021-11-11,Good,2000,60375
117,Tina,HR,60000,2022-06-06,Average,2000,62000
118,Riya,IT,58000,2020-02-29,Excellent,2000,60000
119,Amit,Finance,64000,2023-03-03,Good,2000,66000

### Q67. Remove column using `drop()`.
> 💡 **Hint:** `df.drop(columns=["col1","col2"])`. Always use the `columns=` parameter to be explicit.

---

In [442]:
df_sorting_index.drop(columns=['Salary'])

            Name Department Joining_Date Performance  Bonus  Total_salary
Emp_ID
100         Bapu         IT   2022-01-15        Good   2000         52000
101        Parag         HR   2021-06-20   Excellent   2000         57000
102     Sanchita    Finance   2020-03-10     Average   2000         62000
103        Rohit         IT   2022-08-01        Good   2000         60375
104        Virat      Sales   2021-12-05   Excellent   2000         67000
105       Sachin         HR   2023-02-14     Average   2000         54000
106        Dipak    Finance   2019-09-09   Excellent   2000         60000
107       Ramesh         IT   2022-07-07        Good   2000         59000
108         Asha      Sales   2020-11-11     Average   2000         64000
109        Neha)         HR   2021-05-18   Excellent   2000         60375
110        Kiran         IT   2022-03-22        Good   2000         56000
111         Anil    Finance   2020-10-10     Average   2000         63000
112        Pooja      Sales   2023-01-01   Excellent   2000         60375
113        Sneha         HR   2021-04-12        Good   2000         61000
114         Ajay         IT   2022-09-15     Average   2000         58000
115          Raj    Finance   2020-08-20   Excellent   2000         65000
116         Maya      Sales   2021-11-11        Good   2000         60375
117         Tina         HR   2022-06-06     Average   2000         62000
118         Riya         IT   2020-02-29   Excellent   2000         60000
119         Amit    Finance   2023-03-03        Good   2000         66000

### Q68. Remove rows using `drop()`.
> 💡 **Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.

---

In [443]:
# df_sorting_index.drop(index=[101,'103A',104,109])

### Q69. Use `map()` on a column.
> 💡 **Hint:** `df["col"].map({"a": 1, "b": 2})` substitutes values using a dict. Pass a function for element-wise transformation.

---

In [444]:
# rating = pd.Series({'Excellent':3,'Good':2,'Average':1})
# df_sorting_index['Rating']=df_sorting_index['Performance'].map(rating)
# df_sorting_index

In [445]:
# df_sorting_index=df_sorting_index.reset_index()
df_sorting_index['Salary'].map(lambda x:x+1000)

Emp_ID
100    51000
101    56000
102    61000
103    59375
104    66000
105    53000
106    59000
107    58000
108    63000
109    59375
110    55000
111    62000
112    59375
113    60000
114    57000
115    64000
116    59375
117    61000
118    59000
119    65000
Name: Salary, dtype: int64

In [446]:
df_sorting_index

,Name,Department,Salary,Joining_Date,Performance,Bonus,Total_salary
Emp_ID,,,,,,,
100,Bapu,IT,50000,2022-01-15,Good,2000,52000
101,Parag,HR,55000,2021-06-20,Excellent,2000,57000
102,Sanchita,Finance,60000,2020-03-10,Average,2000,62000
103,Rohit,IT,58375,2022-08-01,Good,2000,60375
104,Virat,Sales,65000,2021-12-05,Excellent,2000,67000
105,Sachin,HR,52000,2023-02-14,Average,2000,54000
106,Dipak,Finance,58000,2019-09-09,Excellent,2000,60000
107,Ramesh,IT,57000,2022-07-07,Good,2000,59000
108,Asha,Sales,62000,2020-11-11,Average,2000,64000
109,Neha),HR,58375,2021-05-18,Excellent,2000,60375
110,Kiran,IT,54000,2022-03-22,Good,2000,56000
111,Anil,Finance,61000,2020-10-10,Average,2000,63000
112,Pooja,Sales,58375,2023-01-01,Excellent,2000,60375
113,Sneha,HR,59000,2021-04-12,Good,2000,61000
114,Ajay,IT,56000,2022-09-15,Average,2000,58000
115,Raj,Finance,63000,2020-08-20,Excellent,2000,65000
116,Maya,Sales,58375,2021-11-11,Good,2000,60375
117,Tina,HR,60000,2022-06-06,Average,2000,62000
118,Riya,IT,58000,2020-02-29,Excellent,2000,60000
119,Amit,Finance,64000,2023-03-03,Good,2000,66000

### Q70. Apply function using `apply()`.
> 💡 **Hint:** `df["col"].apply(func)` for a Series. `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.

---

In [447]:
def salary_increment(sal):
    if sal>=50000:
        return "Average salary"
    elif sal == 0:
        return 'Salary not defined'
    elif sal<50000 :
        return 'Below average salary'

In [448]:
df_sorting_index['Salary'].apply(salary_increment)

Emp_ID
100    Average salary
101    Average salary
102    Average salary
103    Average salary
104    Average salary
105    Average salary
106    Average salary
107    Average salary
108    Average salary
109    Average salary
110    Average salary
111    Average salary
112    Average salary
113    Average salary
114    Average salary
115    Average salary
116    Average salary
117    Average salary
118    Average salary
119    Average salary
Name: Salary, dtype: str

### Q71. Apply element-wise using `applymap()` / `map()`.
> 💡 **Hint:** In older pandas use `df.applymap(func)`. In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.

---

In [449]:
data_frame_map=df_sorting_index[['Salary','Total_salary']]
data_frame_map.map(lambda x: x*100)

         Salary  Total_salary
Emp_ID
100     5000000       5200000
101     5500000       5700000
102     6000000       6200000
103     5837500       6037500
104     6500000       6700000
105     5200000       5400000
106     5800000       6000000
107     5700000       5900000
108     6200000       6400000
109     5837500       6037500
110     5400000       5600000
111     6100000       6300000
112     5837500       6037500
113     5900000       6100000
114     5600000       5800000
115     6300000       6500000
116     5837500       6037500
117     6000000       6200000
118     5800000       6000000
119     6400000       6600000

### Q72. Chain multiple operations.
> 💡 **Hint:** Use method chaining with `(df.copy().loc[...].sort_values(...)[cols].assign(...).reset_index(drop=True))` — wrap in parentheses for multi-line readability.

---

In [451]:
salary_mean=df['Salary'].mean()
print(salary_mean)

df_result=(df.fillna(df['Salary'].mean())
.sort_values('Salary')
.assign(
        Bonus=lambda x: x['Salary'] * 0.10,
        Total_Salary=lambda x: x['Salary'] + x['Bonus']
    )
.query('Salary > @salary_mean')
.reset_index(drop=True)
)
df_result

KeyError: 'Salary'

In [ ]:
# dataframe for questions 72 

import pandas as pd
import numpy as np

np.random.seed(42)

df = pd.DataFrame({
    'Emp_ID': range(101, 121),

    'Name': ['Bapu','Parag','Rohit','Sachin','Dipak',
             'Virat','Amit','Neha','Priya','Kiran',
             'Pooja','Ajay','Raj','Sneha','Ankit',
             'Meena','Ravi','Sonal','Vijay','Ritu'],

    'Department': np.random.choice(
        ['IT','HR','Finance','Sales'],
        20
    ),

    'Age': np.random.randint(22, 50, 20),

    'Salary': np.random.randint(
        30000, 120000, 20
    ).astype(float),

    'Experience': np.random.randint(
        1, 15, 20
    ),

    'Performance': np.random.choice(
        ['Excellent','Good','Average'],
        20
    )
})

# Add missing values
df.loc[[3, 8, 15], 'Salary'] = np.nan

# Add a duplicate row
df = pd.concat(
    [df, df.iloc[[5]]],
    ignore_index=True
)

print(df)

    Emp_ID    Name Department  Age    Salary  Experience Performance
0      101    Bapu    Finance   43   32747.0          10        Good
1      102   Parag      Sales   42   89150.0           5        Good
2      103   Rohit         IT   23   95725.0           2        Good
3      104  Sachin    Finance   45       NaN           4   Excellent
4      105   Dipak    Finance   33   65773.0          12     Average
5      106   Virat      Sales   27   97435.0          12        Good
6      107    Amit         IT   23   86886.0           7        Good
7      108    Neha         IT   49   96803.0          12        Good
8      109   Priya    Finance   42       NaN          13        Good
9      110   Kiran         HR   22   41394.0           8        Good
10     111   Pooja    Finance   33   99092.0           3        Good
11     112    Ajay    Finance   47   33890.0          14     Average
12     113     Raj    Finance   43   71606.0           1     Average
13     114   Sneha    Finance   33  110038.0           4        Good
14     115   Ankit      Sales   46  117313.0           2     Average
15     116   Meena         IT   38       NaN           8   Excellent
16     117    Ravi      Sales   48   38792.0           4        Good
17     118   Sonal      Sales   48  103969.0           2   Excellent
18     119   Vijay      Sales   31   73001.0          14   Excellent
19     120    Ritu    Finance   49  106552.0           6        Good
20     106   Virat      Sales   27   97435.0          12        Good

### Q73. Normalize numeric columns (Min-Max).
> 💡 **Hint:** `(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())` — result is in range [0, 1].

---

In [ ]:
normalisation_df = (df_result['Total_Salary'] - df_result['Total_Salary'].min())/(df_result['Total_Salary'].max() - df_result['Total_Salary'].min())
normalisation_df
df_result['Normalisation']= normalisation_df
df_result

df_result['Normalisation'].between(0,1)

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
Name: Normalisation, dtype: bool

### Q74. Scale numerical data (Z-score standardization).
> 💡 **Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()` — result has mean=0 and std=1.

---

In [ ]:
(df_result['Total_Salary'] - df_result['Total_Salary'].mean())/df_result['Total_Salary'].std(ddof=1)

0    -1.478251
1    -1.223748
2    -0.484633
3    -0.363452
4    -0.292407
5    -0.292407
6    -0.106138
7     0.442100
8     0.732462
9     1.124334
10    1.942138
Name: Total_Salary, dtype: float64

### Q75. Rank values in a column.
> 💡 **Hint:** `df["col"].rank()` — use `ascending=False` for descending rank, `method="dense"` to avoid gaps.

---

In [ ]:
df_result['Rank']= df_result['Salary'].rank(ascending=False,method='dense')
df_result

rank_1=df_result[df_result['Rank'] <3]
print(rank_1)

    Emp_ID   Name Department  Age    Salary  Experience Performance    Bonus  \
9      114  Sneha    Finance   33  110038.0           4        Good  11003.8
10     115  Ankit      Sales   46  117313.0           2     Average  11731.3

    Total_Salary  Normalisation  Rank
9       121041.8       0.760903   2.0
10      129044.3       1.000000   1.0

### Q76. Create bins using `cut()`.
> 💡 **Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or `pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.

---

In [ ]:
pd.cut(df['tip'],bins=[0,25,50,57,100],labels=['LOW','MID','HIGH','TOP'])

0      LOW
1      LOW
2      LOW
3      LOW
4      LOW
      ...
239    LOW
240    LOW
241    LOW
242    LOW
243    LOW
Name: tip, Length: 244, dtype: category
Categories (4, str): ['LOW' < 'MID' < 'HIGH' < 'TOP']

In [ ]:
pd.cut(df['total_bill'],bins=4)

0      (15.005, 26.94]
1      (3.022, 15.005]
2      (15.005, 26.94]
3      (15.005, 26.94]
4      (15.005, 26.94]
            ...
239    (26.94, 38.875]
240    (26.94, 38.875]
241    (15.005, 26.94]
242    (15.005, 26.94]
243    (15.005, 26.94]
Name: total_bill, Length: 244, dtype: category
Categories (4, interval[float64, right]): [(3.022, 15.005] < (15.005, 26.94] < (26.94, 38.875] < (38.875, 50.81]]

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Q77. Create bins using `qcut()`.
> 💡 **Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** (quantile-based) bins. Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.

---

In [ ]:
pd.qcut(df['total_bill'],labels=['Q1','Q2','Q3','Q4','Q5','Q6'],q=6)

0      Q3
1      Q1
2      Q4
3      Q5
4      Q5
       ..
239    Q6
240    Q5
241    Q5
242    Q4
243    Q4
Name: total_bill, Length: 244, dtype: category
Categories (6, str): ['Q1' < 'Q2' < 'Q3' < 'Q4' < 'Q5' < 'Q6']

### Q78. Count unique values.
> 💡 **Hint:** `df["col"].nunique()` for the count, `df["col"].value_counts()` for frequency per unique value.

---

In [ ]:
df['total_bill'].nunique() #returns the number of unique (distinct) values in the total_bill column.

229

In [ ]:
df['total_bill'].value_counts() #It counts the frequency (occurrence) of each unique value in a Series.

total_bill
13.42    3
10.34    2
21.01    2
10.33    2
17.92    2
        ..
29.03    1
27.18    1
22.67    1
17.82    1
18.78    1
Name: count, Length: 229, dtype: int64

### Q79. Replace multiple values at once.
> 💡 **Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or use a list: `df.replace(["old1","old2"], "new")`.

---

In [ ]:
df1.replace([90,80],102)

  First_Name  Marks  Multiplier  Gender
0   Sanchita    102          10  Female
1       Bapu    102          10    Male
2      parag     50          10    Male

In [ ]:
df1.replace({'First_Name' :{'Sanchita':'Sonmali','Bapu':'Chaudhari'}})

  First_Name  Marks  Multiplier  Gender
0    Sonmali     90          10  Female
1  Chaudhari     80          10    Male
2      parag     50          10    Male

### Q80. Create flag column based on condition.
> 💡 **Hint:** `df["flag"] = (df["col"] > threshold).astype(int)` — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.

---

In [ ]:
df1['Where_flag']=np.where(df1['Marks']>80,1,0)
df1

  First_Name  Marks  Multiplier  Gender  Flag  Where_flag
0   Sanchita     90          10  Female     1           1
1       Bapu     80          10    Male     1           0
2      parag     50          10    Male     0           0

In [ ]:
df1['Flag']= (df1['Marks']>60).astype('int')
df1

  First_Name  Marks  Multiplier  Gender  Flag
0   Sanchita     90          10  Female     1
1       Bapu     80          10    Male     1
2      parag     50          10    Male     0

## 🔹 Section 5: Iteration, GroupBy & Pivot (Q81–Q100)

---

### Q81. Iterate over rows using `iterrows()`.
> 💡 **Hint:** `for idx, row in df.iterrows():` — `idx` is the index label, `row` is a Series with column values.

---

In [ ]:
for idx,row in df.iterrows():
    print(row)

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object
total_bill     10.34
tip             1.66
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 1, dtype: object
total_bill     21.01
tip              3.5
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 2, dtype: object
total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object
total_bill     24.59
tip             3.61
sex           Female
smoker            No
day              Sun
time          Dinner
size               4
Name: 4, dtype: object
total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object
total_bill      8.77
tip              2.0
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 6, dtype: object
total_bill     26.88
tip             3.12
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 7, dtype: object
total_bill     15.04
tip             1.96
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 8, dtype: object
total_bill     14.78
tip             3.23
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 9, dtype: object
total_bill     10.27
tip             1.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 10, dtype: object
total_bill     35.26
tip              5.0
sex           Female
smoker            No
day              Sun
time          Dinner
size               4
Name: 11, dtype: object
total_bill     15.42
tip             1.57
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 12, dtype: object
total_bill     18.43
tip              3.0
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 13, dtype: object
total_bill     14.83
tip             3.02
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 14, dtype: object
total_bill     21.58
tip             3.92
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 15, dtype: object
total_bill     10.33
tip             1.67
sex           Female
smoker            No
day              Sun
time          Dinner
size               3
Name: 16, dtype: object
total_bill     16.29
tip             3.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 17, dtype: object
total_bill     16.97
tip              3.5
sex           Female
smoker            No
day              Sun
time          Dinner
size               3
Name: 18, dtype: object
total_bill     20.65
tip             3.35
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 19, dtype: object
total_bill     17.92
tip             4.08
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 20, dtype: object
total_bill     20.29
tip             2.75
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 21, dtype: object
total_bill     15.77
tip             2.23
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 22, dtype: object
total_bill     39.42
tip             7.58
sex             Male
smoker            No
day              Sat
time          Dinner
size               4
Name: 23, dtype: object
total_bill     19.82
tip             3.18
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 24, dtype: object
total_bill     17.81
tip             2.34
sex             Male
smoker            No
day              Sat
time          Dinner
size               4
Name: 25, dtype: object
total_bill     13.37
tip              2.0
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 26, dtype: object
total_bill     12.69
tip              2.0
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 27, dtype: object
total_bill      21.7
tip              4.3
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 28, dtype: object
total_bill     19.65
tip              3.0
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 29, dtype: object
total_bill      9.55
tip             1.45
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 30, dtype: object
total_bill     18.35
tip              2.5
sex             Male
smoker            No
day              Sat
time          Dinner
size               4
Name: 31, dtype: object
total_bill     15.06
tip              3.0
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 32, dtype: object
total_bill     20.69
tip             2.45
sex           Female
smoker            No
day              Sat
time          Dinner
size               4
Name: 33, dtype: object
total_bill     17.78
tip             3.27
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 34, dtype: object
total_bill     24.06
tip              3.6
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 35, dtype: object
total_bill     16.31
tip              2.0
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 36, dtype: object
total_bill     16.93
tip             3.07
sex           Female
smoker            No
day              Sat
time          Dinner
size               3
Name: 37, dtype: object
total_bill     18.69
tip             2.31
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 38, dtype: object
total_bill     31.27
tip              5.0
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 39, dtype: object
total_bill     16.04
tip             2.24
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 40, dtype: object
total_bill     17.46
tip             2.54
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 41, dtype: object
total_bill     13.94
tip             3.06
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 42, dtype: object
total_bill      9.68
tip             1.32
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 43, dtype: object
total_bill      30.4
tip              5.6
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 44, dtype: object
total_bill     18.29
tip              3.0
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 45, dtype: object
total_bill     22.23
tip              5.0
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 46, dtype: object
total_bill      32.4
tip              6.0
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 47, dtype: object
total_bill     28.55
tip             2.05
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 48, dtype: object
total_bill     18.04
tip              3.0
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 49, dtype: object
total_bill     12.54
tip              2.5
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 50, dtype: object
total_bill     10.29
tip              2.6
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 51, dtype: object
total_bill     34.81
tip              5.2
sex           Female
smoker            No
day              Sun
time          Dinner
size               4
Name: 52, dtype: object
total_bill      9.94
tip             1.56
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 53, dtype: object
total_bill     25.56
tip             4.34
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 54, dtype: object
total_bill     19.49
tip             3.51
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 55, dtype: object
total_bill     38.01
tip              3.0
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               4
Name: 56, dtype: object
total_bill     26.41
tip              1.5
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 57, dtype: object
total_bill     11.24
tip             1.76
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 58, dtype: object
total_bill     48.27
tip             6.73
sex             Male
smoker            No
day              Sat
time          Dinner
size               4
Name: 59, dtype: object
total_bill     20.29
tip             3.21
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 60, dtype: object
total_bill     13.81
tip              2.0
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 61, dtype: object
total_bill     11.02
tip             1.98
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 62, dtype: object
total_bill     18.29
tip             3.76
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               4
Name: 63, dtype: object
total_bill     17.59
tip             2.64
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 64, dtype: object
total_bill     20.08
tip             3.15
sex             Male
smoker            No
day              Sat
time          Dinner
size               3
Name: 65, dtype: object
total_bill     16.45
tip             2.47
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 66, dtype: object
total_bill      3.07
tip              1.0
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               1
Name: 67, dtype: object
total_bill     20.23
tip             2.01
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 68, dtype: object
total_bill     15.01
tip             2.09
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 69, dtype: object
total_bill     12.02
tip             1.97
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 70, dtype: object
total_bill     17.07
tip              3.0
sex           Female
smoker            No
day              Sat
time          Dinner
size               3
Name: 71, dtype: object
total_bill     26.86
tip             3.14
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 72, dtype: object
total_bill     25.28
tip              5.0
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 73, dtype: object
total_bill     14.73
tip              2.2
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 74, dtype: object
total_bill     10.51
tip             1.25
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 75, dtype: object
total_bill     17.92
tip             3.08
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 76, dtype: object
total_bill     27.2
tip             4.0
sex            Male
smoker           No
day            Thur
time          Lunch
size              4
Name: 77, dtype: object
total_bill    22.76
tip             3.0
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 78, dtype: object
total_bill    17.29
tip            2.71
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 79, dtype: object
total_bill    19.44
tip             3.0
sex            Male
smoker          Yes
day            Thur
time          Lunch
size              2
Name: 80, dtype: object
total_bill    16.66
tip             3.4
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 81, dtype: object
total_bill     10.07
tip             1.83
sex           Female
smoker            No
day             Thur
time           Lunch
size               1
Name: 82, dtype: object
total_bill    32.68
tip             5.0
sex            Male
smoker          Yes
day            Thur
time          Lunch
size              2
Name: 83, dtype: object
total_bill    15.98
tip            2.03
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 84, dtype: object
total_bill     34.83
tip             5.17
sex           Female
smoker            No
day             Thur
time           Lunch
size               4
Name: 85, dtype: object
total_bill    13.03
tip             2.0
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 86, dtype: object
total_bill    18.28
tip             4.0
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 87, dtype: object
total_bill    24.71
tip            5.85
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 88, dtype: object
total_bill    21.16
tip             3.0
sex            Male
smoker           No
day            Thur
time          Lunch
size              2
Name: 89, dtype: object
total_bill     28.97
tip              3.0
sex             Male
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 90, dtype: object
total_bill     22.49
tip              3.5
sex             Male
smoker            No
day              Fri
time          Dinner
size               2
Name: 91, dtype: object
total_bill      5.75
tip              1.0
sex           Female
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 92, dtype: object
total_bill     16.32
tip              4.3
sex           Female
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 93, dtype: object
total_bill     22.75
tip             3.25
sex           Female
smoker            No
day              Fri
time          Dinner
size               2
Name: 94, dtype: object
total_bill     40.17
tip             4.73
sex             Male
smoker           Yes
day              Fri
time          Dinner
size               4
Name: 95, dtype: object
total_bill     27.28
tip              4.0
sex             Male
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 96, dtype: object
total_bill     12.03
tip              1.5
sex             Male
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 97, dtype: object
total_bill     21.01
tip              3.0
sex             Male
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 98, dtype: object
total_bill     12.46
tip              1.5
sex             Male
smoker            No
day              Fri
time          Dinner
size               2
Name: 99, dtype: object
total_bill     11.35
tip              2.5
sex           Female
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 100, dtype: object
total_bill     15.38
tip              3.0
sex           Female
smoker           Yes
day              Fri
time          Dinner
size               2
Name: 101, dtype: object
total_bill      44.3
tip              2.5
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               3
Name: 102, dtype: object
total_bill     22.42
tip             3.48
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 103, dtype: object
total_bill     20.92
tip             4.08
sex           Female
smoker            No
day              Sat
time          Dinner
size               2
Name: 104, dtype: object
total_bill     15.36
tip             1.64
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 105, dtype: object
total_bill     20.49
tip             4.06
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 106, dtype: object
total_bill     25.21
tip             4.29
sex             Male
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 107, dtype: object
total_bill     18.24
tip             3.76
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 108, dtype: object
total_bill     14.31
tip              4.0
sex           Female
smoker           Yes
day              Sat
time          Dinner
size               2
Name: 109, dtype: object
total_bill      14.0
tip              3.0
sex             Male
smoker            No
day              Sat
time          Dinner
size               2
Name: 110, dtype: object
total_bill      7.25
tip              1.0
sex           Female
smoker            No
day              Sat
time          Dinner
size               1
Name: 111, dtype: object
total_bill     38.07
tip              4.0
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 112, dtype: object
total_bill     23.95
tip             2.55
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 113, dtype: object
total_bill     25.71
tip              4.0
sex           Female
smoker            No
day              Sun
time          Dinner
size               3
Name: 114, dtype: object
total_bill     17.31
tip              3.5
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 115, dtype: object
total_bill     29.93
tip             5.07
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 116, dtype: object
total_bill     10.65
tip              1.5
sex           Female

### Q82. Iterate using `itertuples()`.
> 💡 **Hint:** `for row in df.itertuples():` — `row.col_name` accesses values. **Faster** than `iterrows()` due to named tuples.

---

In [ ]:
for row in df.itertuples():
    print(row[0],row[1],row[2],row[3])

0 16.99 1.01 Female
1 10.34 1.66 Male
2 21.01 3.5 Male
3 23.68 3.31 Male
4 24.59 3.61 Female
5 25.29 4.71 Male
6 8.77 2.0 Male
7 26.88 3.12 Male
8 15.04 1.96 Male
9 14.78 3.23 Male
10 10.27 1.71 Male
11 35.26 5.0 Female
12 15.42 1.57 Male
13 18.43 3.0 Male
14 14.83 3.02 Female
15 21.58 3.92 Male
16 10.33 1.67 Female
17 16.29 3.71 Male
18 16.97 3.5 Female
19 20.65 3.35 Male
20 17.92 4.08 Male
21 20.29 2.75 Female
22 15.77 2.23 Female
23 39.42 7.58 Male
24 19.82 3.18 Male
25 17.81 2.34 Male
26 13.37 2.0 Male
27 12.69 2.0 Male
28 21.7 4.3 Male
29 19.65 3.0 Female
30 9.55 1.45 Male
31 18.35 2.5 Male
32 15.06 3.0 Female
33 20.69 2.45 Female
34 17.78 3.27 Male
35 24.06 3.6 Male
36 16.31 2.0 Male
37 16.93 3.07 Female
38 18.69 2.31 Male
39 31.27 5.0 Male
40 16.04 2.24 Male
41 17.46 2.54 Male
42 13.94 3.06 Male
43 9.68 1.32 Male
44 30.4 5.6 Male
45 18.29 3.0 Male
46 22.23 5.0 Male
47 32.4 6.0 Male
48 28.55 2.05 Male
49 18.04 3.0 Male
50 12.54 2.5 Male
51 10.29 2.6 Female
52 34.81 5.2 Female
53 9.94 1.56 Male
54 25.56 4.34 Male
55 19.49 3.51 Male
56 38.01 3.0 Male
57 26.41 1.5 Female
58 11.24 1.76 Male
59 48.27 6.73 Male
60 20.29 3.21 Male
61 13.81 2.0 Male
62 11.02 1.98 Male
63 18.29 3.76 Male
64 17.59 2.64 Male
65 20.08 3.15 Male
66 16.45 2.47 Female
67 3.07 1.0 Female
68 20.23 2.01 Male
69 15.01 2.09 Male
70 12.02 1.97 Male
71 17.07 3.0 Female
72 26.86 3.14 Female
73 25.28 5.0 Female
74 14.73 2.2 Female
75 10.51 1.25 Male
76 17.92 3.08 Male
77 27.2 4.0 Male
78 22.76 3.0 Male
79 17.29 2.71 Male
80 19.44 3.0 Male
81 16.66 3.4 Male
82 10.07 1.83 Female
83 32.68 5.0 Male
84 15.98 2.03 Male
85 34.83 5.17 Female
86 13.03 2.0 Male
87 18.28 4.0 Male
88 24.71 5.85 Male
89 21.16 3.0 Male
90 28.97 3.0 Male
91 22.49 3.5 Male
92 5.75 1.0 Female
93 16.32 4.3 Female
94 22.75 3.25 Female
95 40.17 4.73 Male
96 27.28 4.0 Male
97 12.03 1.5 Male
98 21.01 3.0 Male
99 12.46 1.5 Male
100 11.35 2.5 Female
101 15.38 3.0 Female
102 44.3 2.5 Female
103 22.42 3.48 Female
104 20.92 4.08 Female
105 15.36 1.64 Male
106 20.49 4.06 Male
107 25.21 4.29 Male
108 18.24 3.76 Male
109 14.31 4.0 Female
110 14.0 3.0 Male
111 7.25 1.0 Female
112 38.07 4.0 Male
113 23.95 2.55 Male
114 25.71 4.0 Female
115 17.31 3.5 Female
116 29.93 5.07 Male
117 10.65 1.5 Female
118 12.43 1.8 Female
119 24.08 2.92 Female
120 11.69 2.31 Male
121 13.42 1.68 Female
122 14.26 2.5 Male
123 15.95 2.0 Male
124 12.48 2.52 Female
125 29.8 4.2 Female
126 8.52 1.48 Male
127 14.52 2.0 Female
128 11.38 2.0 Female
129 22.82 2.18 Male
130 19.08 1.5 Male
131 20.27 2.83 Female
132 11.17 1.5 Female
133 12.26 2.0 Female
134 18.26 3.25 Female
135 8.51 1.25 Female
136 10.33 2.0 Female
137 14.15 2.0 Female
138 16.0 2.0 Male
139 13.16 2.75 Female
140 17.47 3.5 Female
141 34.3 6.7 Male
142 41.19 5.0 Male
143 27.05 5.0 Female
144 16.43 2.3 Female
145 8.35 1.5 Female
146 18.64 1.36 Female
147 11.87 1.63 Female
148 9.78 1.73 Male
149 7.51 2.0 Male
150 14.07 2.5 Male
151 13.13 2.0 Male
152 17.26 2.74 Male
153 24.55 2.0 Male
154 19.77 2.0 Male
155 29.85 5.14 Female
156 48.17 5.0 Male
157 25.0 3.75 Female
158 13.39 2.61 Female
159 16.49 2.0 Male
160 21.5 3.5 Male
161 12.66 2.5 Male
162 16.21 2.0 Female
163 13.81 2.0 Male
164 17.51 3.0 Female
165 24.52 3.48 Male
166 20.76 2.24 Male
167 31.71 4.5 Male
168 10.59 1.61 Female
169 10.63 2.0 Female
170 50.81 10.0 Male
171 15.81 3.16 Male
172 7.25 5.15 Male
173 31.85 3.18 Male
174 16.82 4.0 Male
175 32.9 3.11 Male
176 17.89 2.0 Male
177 14.48 2.0 Male
178 9.6 4.0 Female
179 34.63 3.55 Male
180 34.65 3.68 Male
181 23.33 5.65 Male
182 45.35 3.5 Male
183 23.17 6.5 Male
184 40.55 3.0 Male
185 20.69 5.0 Male
186 20.9 3.5 Female
187 30.46 2.0 Male
188 18.15 3.5 Female
189 23.1 4.0 Male
190 15.69 1.5 Male
191 19.81 4.19 Female
192 28.44 2.56 Male
193 15.48 2.02 Male
194 16.58 4.0 Male
195 7.56 1.44 Male
196 10.34 2.0 Male
197 43.11 5.0 Female
198 13.0 2.0 Female
199 13.51 2.0 Male
200 18.71 4.0 Male
201 12.74 2.01 Female
202 13.0 2.0 Female
203 16.4 2.5 Female
204 20.53 4.0 Male
205 16.47 3.23 Female
206 26.59 3.41 Male
207 38.73 3.0 Male
208 24.27 2.03 Male
209 12.76 2.23 Female
210 30.06 2.0 Male
211 25.89 5.16 Male
212 48.33 9.0 Male
213 13.27 2.5 Female
214 28.17 6.5 Female
215 12.9 1.1 Female
216 28.15 3.0 Male
217 11.59 1.5 Male
218 7.74 1.44 Male
219 30.14 3.09 Female
220 12.16 2.2 Male
221 13.42 3.48 Female
222 8.58 1.92 Male
223 15.98 3.0 Female
224 13.42 1.58 Male
225 16.27 2.5 Female
226 10.09 2.0 Female
227 20.45 3.0 Male
228 13.28 2.72 Male
229 22.12 2.88 Female
230 24.01 2.0 Male
231 15.69 3.0 Male
232 11.61 3.39 Male
233 10.77 1.47 Male
234 15.53 3.0 Male
235 10.07 1.25 Male
236 12.6 1.0 Male
237 32.83 1.17 Male
238 35.83 4.67 Female
239 29.03 5.92 Male
240 27.18 2.0 Female
241 22.67 2.0 Male
242 17.82 1.75 Male
243 18.78 3.0 Female

### Q83. Iterate over columns.
> 💡 **Hint:** `for col in df.columns:` then access `df[col]`. Or use `df.items()` which yields `(col_name, Series)` pairs.

---

In [ ]:
for col_name, data in df.items():
    print(col_name)
    print(data)

total_bill
0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64
tip
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
sex
0      Female
1        Male
2        Male
3        Male
4      Female
        ...
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: category
Categories (2, str): ['Male', 'Female']
smoker
0       No
1       No
2       No
3       No
4       No
      ...
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, str): ['Yes', 'No']
day
0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']
time
0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, str): ['Lunch', 'Dinner']
size
0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [ ]:
for col in df.columns:
    
    print(df[col])

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
0      Female
1        Male
2        Male
3        Male
4      Female
        ...
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: category
Categories (2, str): ['Male', 'Female']
0       No
1       No
2       No
3       No
4       No
      ...
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, str): ['Yes', 'No']
0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']
0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, str): ['Lunch', 'Dinner']
0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [ ]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Q84. Avoid iteration using vectorization.
> 💡 **Hint:** Replace `for` loops with direct column operations: `df["new"] = df["a"] * 2 + 1` instead of a loop over rows.

---

In [ ]:
df['new'] = df['tip'] * 2 + 2
df

     total_bill   tip     sex smoker   day    time  size    new
0         16.99  1.01  Female     No   Sun  Dinner     2   4.02
1         10.34  1.66    Male     No   Sun  Dinner     3   5.32
2         21.01  3.50    Male     No   Sun  Dinner     3   9.00
3         23.68  3.31    Male     No   Sun  Dinner     2   8.62
4         24.59  3.61  Female     No   Sun  Dinner     4   9.22
..          ...   ...     ...    ...   ...     ...   ...    ...
239       29.03  5.92    Male     No   Sat  Dinner     3  13.84
240       27.18  2.00  Female    Yes   Sat  Dinner     2   6.00
241       22.67  2.00    Male    Yes   Sat  Dinner     2   6.00
242       17.82  1.75    Male     No   Sat  Dinner     2   5.50
243       18.78  3.00  Female     No  Thur  Dinner     2   8.00

[244 rows x 8 columns]

In [ ]:
# df = df.drop('new',axis=1)
df = df.drop('size',axis=1)
df

     total_bill   tip     sex smoker   day    time
0         16.99  1.01  Female     No   Sun  Dinner
1         10.34  1.66    Male     No   Sun  Dinner
2         21.01  3.50    Male     No   Sun  Dinner
3         23.68  3.31    Male     No   Sun  Dinner
4         24.59  3.61  Female     No   Sun  Dinner
..          ...   ...     ...    ...   ...     ...
239       29.03  5.92    Male     No   Sat  Dinner
240       27.18  2.00  Female    Yes   Sat  Dinner
241       22.67  2.00    Male    Yes   Sat  Dinner
242       17.82  1.75    Male     No   Sat  Dinner
243       18.78  3.00  Female     No  Thur  Dinner

[244 rows x 6 columns]

### Q85. Group data using `groupby()`.
> 💡 **Hint:** `df.groupby("col")["value_col"].mean()` — specify the grouping key and the aggregation in one line.

---

In [ ]:
df.groupby('sex')['total_bill'].mean()

sex
Male      20.744076
Female    18.056897
Name: total_bill, dtype: float64

In [ ]:
df.groupby('sex')['tip'].mean()

sex
Male      3.089618
Female    2.833448
Name: tip, dtype: float64

### Q86. Calculate sum per group.
> 💡 **Hint:** `df.groupby("col")["value"].sum()` — replace `sum` with any aggregation function.

---

In [ ]:
df.groupby('sex')['tip'].sum()

sex
Male      485.07
Female    246.51
Name: tip, dtype: float64

In [ ]:
df.describe()

       total_bill         tip
count  244.000000  244.000000
mean    19.785943    2.998279
std      8.902412    1.383638
min      3.070000    1.000000
25%     13.347500    2.000000
50%     17.795000    2.900000
75%     24.127500    3.562500
max     50.810000   10.000000

### Q87. Calculate multiple aggregations.
> 💡 **Hint:** `df.groupby("col").agg({"col1": "mean", "col2": "sum"})` or `df.groupby("col").agg(name=("col","func"))` for named aggregation.

---

In [ ]:
df.groupby('sex').agg({'total_bill':'mean','tip':'sum'})

        total_bill     tip
sex
Male     20.744076  485.07
Female   18.056897  246.51

### Q88. Group by multiple columns.
> 💡 **Hint:** `df.groupby(["col1","col2"])["value"].mean()` — pass a list of column names.

---

In [ ]:
df.groupby(['sex','smoker']).agg({'total_bill':'mean','tip':'sum'})

               total_bill     tip
sex    smoker
Male   Yes      22.284500  183.07
       No       19.791237  302.00
Female Yes      17.977879   96.74
       No       18.105185  149.77

In [ ]:
df.groupby(['sex','smoker','time'])['total_bill'].mean()

sex     smoker  time
Male    Yes     Lunch     17.374615
                Dinner    23.642553
        No      Lunch     18.486500
                Dinner    20.130130
Female  Yes     Lunch     17.431000
                Dinner    18.215652
        No      Lunch     15.902400
                Dinner    20.004138
Name: total_bill, dtype: float64

### Q89. Filter grouped data.
> 💡 **Hint:** `df.groupby("col").filter(lambda g: g["value"].mean() > threshold)` — keeps entire groups satisfying the condition.

---

In [ ]:
df.groupby(['sex','smoker']).filter(lambda x:x['total_bill'].median() > 20)

     total_bill    tip   sex smoker   day    time
56        38.01   3.00  Male    Yes   Sat  Dinner
58        11.24   1.76  Male    Yes   Sat  Dinner
60        20.29   3.21  Male    Yes   Sat  Dinner
61        13.81   2.00  Male    Yes   Sat  Dinner
62        11.02   1.98  Male    Yes   Sat  Dinner
63        18.29   3.76  Male    Yes   Sat  Dinner
69        15.01   2.09  Male    Yes   Sat  Dinner
76        17.92   3.08  Male    Yes   Sat  Dinner
80        19.44   3.00  Male    Yes  Thur   Lunch
83        32.68   5.00  Male    Yes  Thur   Lunch
90        28.97   3.00  Male    Yes   Fri  Dinner
95        40.17   4.73  Male    Yes   Fri  Dinner
96        27.28   4.00  Male    Yes   Fri  Dinner
97        12.03   1.50  Male    Yes   Fri  Dinner
98        21.01   3.00  Male    Yes   Fri  Dinner
105       15.36   1.64  Male    Yes   Sat  Dinner
106       20.49   4.06  Male    Yes   Sat  Dinner
107       25.21   4.29  Male    Yes   Sat  Dinner
138       16.00   2.00  Male    Yes  Thur   Lunch
170       50.81  10.00  Male    Yes   Sat  Dinner
171       15.81   3.16  Male    Yes   Sat  Dinner
172        7.25   5.15  Male    Yes   Sun  Dinner
173       31.85   3.18  Male    Yes   Sun  Dinner
174       16.82   4.00  Male    Yes   Sun  Dinner
175       32.90   3.11  Male    Yes   Sun  Dinner
176       17.89   2.00  Male    Yes   Sun  Dinner
177       14.48   2.00  Male    Yes   Sun  Dinner
179       34.63   3.55  Male    Yes   Sun  Dinner
180       34.65   3.68  Male    Yes   Sun  Dinner
181       23.33   5.65  Male    Yes   Sun  Dinner
182       45.35   3.50  Male    Yes   Sun  Dinner
183       23.17   6.50  Male    Yes   Sun  Dinner
184       40.55   3.00  Male    Yes   Sun  Dinner
187       30.46   2.00  Male    Yes   Sun  Dinner
189       23.10   4.00  Male    Yes   Sun  Dinner
190       15.69   1.50  Male    Yes   Sun  Dinner
192       28.44   2.56  Male    Yes  Thur   Lunch
193       15.48   2.02  Male    Yes  Thur   Lunch
194       16.58   4.00  Male    Yes  Thur   Lunch
196       10.34   2.00  Male    Yes  Thur   Lunch
199       13.51   2.00  Male    Yes  Thur   Lunch
200       18.71   4.00  Male    Yes  Thur   Lunch
204       20.53   4.00  Male    Yes  Thur   Lunch
206       26.59   3.41  Male    Yes   Sat  Dinner
207       38.73   3.00  Male    Yes   Sat  Dinner
208       24.27   2.03  Male    Yes   Sat  Dinner
210       30.06   2.00  Male    Yes   Sat  Dinner
211       25.89   5.16  Male    Yes   Sat  Dinner
216       28.15   3.00  Male    Yes   Sat  Dinner
217       11.59   1.50  Male    Yes   Sat  Dinner
218        7.74   1.44  Male    Yes   Sat  Dinner
220       12.16   2.20  Male    Yes   Fri   Lunch
222        8.58   1.92  Male    Yes   Fri   Lunch
224       13.42   1.58  Male    Yes   Fri   Lunch
230       24.01   2.00  Male    Yes   Sat  Dinner
231       15.69   3.00  Male    Yes   Sat  Dinner
234       15.53   3.00  Male    Yes   Sat  Dinner
236       12.60   1.00  Male    Yes   Sat  Dinner
237       32.83   1.17  Male    Yes   Sat  Dinner
241       22.67   2.00  Male    Yes   Sat  Dinner

In [ ]:
df.groupby(['sex','smoker']).filter(lambda x:x['total_bill'].mean()>22)

     total_bill    tip   sex smoker   day    time
56        38.01   3.00  Male    Yes   Sat  Dinner
58        11.24   1.76  Male    Yes   Sat  Dinner
60        20.29   3.21  Male    Yes   Sat  Dinner
61        13.81   2.00  Male    Yes   Sat  Dinner
62        11.02   1.98  Male    Yes   Sat  Dinner
63        18.29   3.76  Male    Yes   Sat  Dinner
69        15.01   2.09  Male    Yes   Sat  Dinner
76        17.92   3.08  Male    Yes   Sat  Dinner
80        19.44   3.00  Male    Yes  Thur   Lunch
83        32.68   5.00  Male    Yes  Thur   Lunch
90        28.97   3.00  Male    Yes   Fri  Dinner
95        40.17   4.73  Male    Yes   Fri  Dinner
96        27.28   4.00  Male    Yes   Fri  Dinner
97        12.03   1.50  Male    Yes   Fri  Dinner
98        21.01   3.00  Male    Yes   Fri  Dinner
105       15.36   1.64  Male    Yes   Sat  Dinner
106       20.49   4.06  Male    Yes   Sat  Dinner
107       25.21   4.29  Male    Yes   Sat  Dinner
138       16.00   2.00  Male    Yes  Thur   Lunch
170       50.81  10.00  Male    Yes   Sat  Dinner
171       15.81   3.16  Male    Yes   Sat  Dinner
172        7.25   5.15  Male    Yes   Sun  Dinner
173       31.85   3.18  Male    Yes   Sun  Dinner
174       16.82   4.00  Male    Yes   Sun  Dinner
175       32.90   3.11  Male    Yes   Sun  Dinner
176       17.89   2.00  Male    Yes   Sun  Dinner
177       14.48   2.00  Male    Yes   Sun  Dinner
179       34.63   3.55  Male    Yes   Sun  Dinner
180       34.65   3.68  Male    Yes   Sun  Dinner
181       23.33   5.65  Male    Yes   Sun  Dinner
182       45.35   3.50  Male    Yes   Sun  Dinner
183       23.17   6.50  Male    Yes   Sun  Dinner
184       40.55   3.00  Male    Yes   Sun  Dinner
187       30.46   2.00  Male    Yes   Sun  Dinner
189       23.10   4.00  Male    Yes   Sun  Dinner
190       15.69   1.50  Male    Yes   Sun  Dinner
192       28.44   2.56  Male    Yes  Thur   Lunch
193       15.48   2.02  Male    Yes  Thur   Lunch
194       16.58   4.00  Male    Yes  Thur   Lunch
196       10.34   2.00  Male    Yes  Thur   Lunch
199       13.51   2.00  Male    Yes  Thur   Lunch
200       18.71   4.00  Male    Yes  Thur   Lunch
204       20.53   4.00  Male    Yes  Thur   Lunch
206       26.59   3.41  Male    Yes   Sat  Dinner
207       38.73   3.00  Male    Yes   Sat  Dinner
208       24.27   2.03  Male    Yes   Sat  Dinner
210       30.06   2.00  Male    Yes   Sat  Dinner
211       25.89   5.16  Male    Yes   Sat  Dinner
216       28.15   3.00  Male    Yes   Sat  Dinner
217       11.59   1.50  Male    Yes   Sat  Dinner
218        7.74   1.44  Male    Yes   Sat  Dinner
220       12.16   2.20  Male    Yes   Fri   Lunch
222        8.58   1.92  Male    Yes   Fri   Lunch
224       13.42   1.58  Male    Yes   Fri   Lunch
230       24.01   2.00  Male    Yes   Sat  Dinner
231       15.69   3.00  Male    Yes   Sat  Dinner
234       15.53   3.00  Male    Yes   Sat  Dinner
236       12.60   1.00  Male    Yes   Sat  Dinner
237       32.83   1.17  Male    Yes   Sat  Dinner
241       22.67   2.00  Male    Yes   Sat  Dinner

### Q90. Transform grouped data using `transform()`.
> 💡 **Hint:** `df.groupby("col")["value"].transform("mean")` — returns a Series **same size as the original DataFrame** filled with group statistics.

---

In [ ]:
df.groupby(['sex','time','smoker'])[['total_bill','tip']].transform('mean')

     total_bill       tip
0     20.004138  3.044138
1     20.130130  3.158052
2     20.130130  3.158052
3     20.130130  3.158052
4     20.004138  3.044138
..          ...       ...
239   20.130130  3.158052
240   18.215652  2.949130
241   23.642553  3.123191
242   20.130130  3.158052
243   20.004138  3.044138

[244 rows x 2 columns]

In [ ]:
df.groupby(['sex','time','smoker'])[['total_bill','tip']].transform('mean')
# Each row gets the mean value of its own group.

     total_bill       tip
0     20.004138  3.044138
1     20.130130  3.158052
2     20.130130  3.158052
3     20.130130  3.158052
4     20.004138  3.044138
..          ...       ...
239   20.130130  3.158052
240   18.215652  2.949130
241   23.642553  3.123191
242   20.130130  3.158052
243   20.004138  3.044138

[244 rows x 2 columns]

### Q91. Apply custom function in groupby.
> 💡 **Hint:** `df.groupby("col")["value"].agg(lambda s: s.max() - s.min())` — pass any function that takes a Series and returns a scalar.

---

In [ ]:
df.groupby('smoker')['tip'].agg(lambda x:x.max()-x.min())

smoker
Yes    9.0
No     8.0
Name: tip, dtype: float64

### Q92. Create basic pivot table.
> 💡 **Hint:** `pd.pivot_table(df, values="val", index="row_col", columns="col_col", aggfunc="mean")`.

---

In [ ]:
pd.pivot_table(df,values='total_bill',index='sex',columns='smoker',aggfunc='mean')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [ ]:
pd.pivot_table(df,values='total_bill',columns='smoker',aggfunc='mean')

smoker            Yes         No
total_bill  20.756344  19.188278

In [ ]:
df

     total_bill   tip     sex smoker   day    time
0         16.99  1.01  Female     No   Sun  Dinner
1         10.34  1.66    Male     No   Sun  Dinner
2         21.01  3.50    Male     No   Sun  Dinner
3         23.68  3.31    Male     No   Sun  Dinner
4         24.59  3.61  Female     No   Sun  Dinner
..          ...   ...     ...    ...   ...     ...
239       29.03  5.92    Male     No   Sat  Dinner
240       27.18  2.00  Female    Yes   Sat  Dinner
241       22.67  2.00    Male    Yes   Sat  Dinner
242       17.82  1.75    Male     No   Sat  Dinner
243       18.78  3.00  Female     No  Thur  Dinner

[244 rows x 6 columns]

### Q93. Use multiple aggregation functions in pivot.
> 💡 **Hint:** Pass a list to `aggfunc`: `aggfunc=["mean","max"]` — the result will have a MultiLevel column header.

---

In [ ]:
pd.pivot_table(df,values='total_bill',index='sex',columns='smoker',aggfunc=['mean','median'],margins=True)

             mean                       median
smoker        Yes         No        All    Yes     No     All
sex
Male    22.284500  19.791237  20.744076  20.39  18.24  18.350
Female  17.977879  18.105185  18.056897  16.27  16.69  16.400
All     20.756344  19.188278  19.785943  17.92  17.59  17.795

### Q94. Handle missing values in pivot tables.
> 💡 **Hint:** Use `fill_value=0` in `pivot_table()` to replace NaN with a specific value.

---

### Q95. Add margins (totals) in pivot tables.
> 💡 **Hint:** `margins=True, margins_name="TOTAL"` in `pivot_table()` adds a summary row and column.

---

In [ ]:
pd.pivot_table(df,values='total_bill',index='sex',columns='smoker',aggfunc=['mean','median'],margins=True,margins_name='Total')

             mean                       median
smoker        Yes         No      Total    Yes     No   Total
sex
Male    22.284500  19.791237  20.744076  20.39  18.24  18.350
Female  17.977879  18.105185  18.056897  16.27  16.69  16.400
Total   20.756344  19.188278  19.785943  17.92  17.59  17.795

### Q96. Create multi-level pivot table.
> 💡 **Hint:** Pass lists to `index` and `columns` parameters: `index=["col1","col2"], columns=["col3"]`.

---

In [ ]:
pd.pivot_table(df,values='total_bill',index=['sex','time'],columns=['smoker','day'],aggfunc=['mean','median','std'],margins=True)

                    mean                                                      \
smoker               Yes                                          No
day                 Thur        Fri        Sat        Sun       Thur     Fri
sex    time
Male   Lunch   19.171000  11.386667        NaN        NaN  18.486500     NaN
       Dinner        NaN  25.892000  21.837778  26.141333        NaN  17.475
Female Lunch   19.218571  13.260000        NaN        NaN  15.899167  15.980
       Dinner        NaN  12.200000  20.266667  16.540000  18.780000  22.750
All            19.190588  16.813333  21.276667  24.120000  17.113111  18.420

                                                median  ...          \
smoker                                     All     Yes  ...     All
day                  Sat        Sun               Thur  ...
sex    time                                             ...
Male   Lunch         NaN        NaN  18.048485  17.645  ...  16.580
       Dinner  19.929063  20.403256  21.461452     NaN  ...  19.630
Female Lunch         NaN        NaN  16.339143  16.400  ...  13.420
       Dinner  19.003846  20.824286  19.213077     NaN  ...  17.190
All            19.661778  20.506667  19.785943  16.470  ...  17.795

                     std                                                       \
smoker               Yes                                         No
day                 Thur        Fri        Sat        Sun      Thur       Fri
sex    time
Male   Lunch    6.757421   2.510963        NaN        NaN  8.739134       NaN
       Dinner        NaN  10.383290   9.988045  10.693824       NaN  7.092281
Female Lunch   10.847137   3.093105        NaN        NaN  6.904808       NaN
       Dinner        NaN   4.810121  10.485703   4.854764       NaN       NaN
All             8.355149   9.086388  10.069138  10.442511  7.721728  5.059282


smoker                                  All
day                 Sat       Sun
sex    time
Male   Lunch        NaN       NaN  7.953435
       Dinner  9.779061  8.140559  9.460974
Female Lunch        NaN       NaN  7.500803
       Dinner  6.730219  8.396159  8.202085
All            8.939181  8.130189  8.902412

[5 rows x 27 columns]

### Q97. Convert DataFrame to pivot format.
> 💡 **Hint:** `df.pivot(index="row_key", columns="col_key", values="value")` — requires **unique** combinations of row/column keys (no aggregation).

---

In [ ]:
df = pd.DataFrame({
    'sex':['Male','Female'],
    'time':['Dinner','Dinner'],
    'tip':[5,6]
})

df.pivot(index='sex', columns='time', values='tip')

time    Dinner
sex
Female       6
Male         5

In [ ]:
print(df['sex'].unique())
print(df['time'].duplicated())

<StringArray>
['Male', 'Female']
Length: 2, dtype: str
0    False
1     True
Name: time, dtype: bool

### Q98. Compare pivot vs groupby.
> 💡 **Hint:** `groupby()` is more flexible and returns a flat structure. `pivot_table()` gives a 2D grid and handles duplicates with aggregation. `pivot()` does **no aggregation** and fails on duplicates.

---

### Q99. Build summary report using pivot table.
> 💡 **Hint:** Combine `pivot_table()` with `margins=True` and `fill_value=0`. Chain `.round(2)` for presentation. Export with `.to_csv()` or `.to_excel()`.

---

In [ ]:

pd.pivot_table(
    df_operation,
    values='Salary',
    index='Department',
    aggfunc=['mean','median'],
    margins=True
)

               mean   median
             Salary   Salary
Department
Finance     61200.0  61000.0
HR          56875.0  58375.0
IT          55562.5  56500.0
Sales       60937.5  60187.5
All         58375.0  58375.0

### Q100. Create an end-to-end analysis workflow.
> 💡 **Hint:** Follow this pipeline:  
> 1. Load data → 2. Inspect (shape, dtypes, nulls) → 3. Clean (fillna, drop_duplicates) → 4. Feature engineer → 5. GroupBy/pivot analysis → 6. Sort and rank → 7. Export results.

---

In [466]:
import numpy as np
import pandas as pd
ipl = pd.read_csv(r'D:\DataSet\ball_by_ball_data.csv')
ipl.head(5)
ipl.head(20)

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,0,0,0,...,False,False,0,0,1,0,0,NaN,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,1,0,...,False,False,0,0,0,0,0,NaN,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,2,0,...,False,False,1,0,0,0,0,NaN,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,3,0,...,False,False,0,0,0,0,0,NaN,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,4,0,...,False,False,0,0,0,0,0,NaN,False,1
5,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,5,0,...,False,False,0,0,0,0,0,NaN,False,1
6,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,6,0,...,False,False,0,0,1,0,0,NaN,False,1
7,2008,335982,BB McCullum,Z Khan,SC Ganguly,6,1,1,0,0,...,False,False,0,0,0,0,0,NaN,False,1
8,2008,335982,BB McCullum,Z Khan,SC Ganguly,6,1,1,1,4,...,False,False,0,0,0,0,0,NaN,False,1
9,2008,335982,BB McCullum,Z Khan,SC Ganguly,6,1,1,2,4,...,False,False,0,0,0,0,0,NaN,False,1
10,2008,335982,BB McCullum,Z Khan,SC Ganguly,6,1,1,3,6,...,False,False,0,0,0,0,0,NaN,False,1
11,2008,335982,BB McCullum,Z Khan,SC Ganguly,6,1,1,4,4,...,False,False,0,0,0,0,0,NaN,False,1
12,2008,335982,BB McCullum,Z Khan,SC Ganguly,6,1,1,5,0,...,False,False,0,0,0,0,0,NaN,False,1
13,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,2,0,0,...,False,False,0,0,0,0,0,NaN,False,1
14,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,2,1,0,...,False,False,0,0,0,0,0,NaN,False,1
15,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,2,2,0,...,False,False,0,0,1,0,0,NaN,False,1
16,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,2,3,4,...,False,False,0,0,0,0,0,NaN,False,1
17,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,2,4,1,...,False,False,0,0,0,0,0,NaN,False,1
18,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,2,5,0,...,False,False,0,0,0,0,0,NaN,False,1
19,2008,335982,BB McCullum,AA Noffke,SC Ganguly,6,1,3,0,0,...,False,False,5,0,0,0,0,NaN,False,1

In [467]:
print("Shape of DataSet:", ipl.shape)
print("\nData Types of each column:")
print(ipl.dtypes)
print("\nNull Values is DataSet")
print(pd.isnull(ipl).sum())
print("\n Description of dataset ")
print(ipl.describe)

Shape of DataSet: (288226, 30)

Data Types of each column:
season_id            int64
match_id             int64
batter                 str
bowler                 str
non_striker            str
team_batting         int64
team_bowling         int64
over_number          int64
ball_number          int64
batter_runs          int64
extras               int64
total_runs           int64
batsman_type           str
bowler_type            str
player_out             str
fielders_involved      str
is_wicket             bool
is_wide_ball          bool
is_no_ball            bool
is_leg_bye            bool
is_bye                bool
is_penalty            bool
wide_ball_runs       int64
no_ball_runs         int64
leg_bye_runs         int64
bye_runs             int64
penalty_runs         int64
wicket_kind            str
is_super_over         bool
innings              int64
dtype: object

Null Values is DataSet
season_id                 0
match_id                  0
batter                    0
bowler                    0
non_striker               0
team_batting              0
team_bowling              0
over_number               0
ball_number               0
batter_runs               0
extras                    0
total_runs                0
batsman_type            239
bowler_type             339
player_out           273886
fielders_involved    273886
is_wicket                 0
is_wide_ball              0
is_no_ball                0
is_leg_bye                0
is_bye                    0
is_penalty                0
wide_ball_runs            0
no_ball_runs              0
leg_bye_runs              0
bye_runs                  0
penalty_runs              0
wicket_kind          273886
is_super_over             0
innings                   0
dtype: int64

 Description of dataset
<bound method NDFrame.describe of         season_id  match_id           batter          bowler      non_striker  \
0            2008    335982       SC Ganguly         P Kumar      BB McCullum
1            2008    335982      BB McCullum         P Kumar       SC Ganguly
2            2008    335982      BB McCullum         P Kumar       SC Ganguly
3            2008    335982      BB McCullum         P Kumar       SC Ganguly
4            2008    335982      BB McCullum         P Kumar       SC Ganguly
...           ...       ...              ...             ...              ...
288221       2026   1529286         T Stubbs       JC Archer  Ashutosh Sharma
288222       2026   1529286  Ashutosh Sharma       JC Archer         T Stubbs
288223       2026   1529286         T Stubbs       JC Archer  Ashutosh Sharma
288224       2026   1529286  Ashutosh Sharma  Brijesh Sharma         T Stubbs
288225       2026   1529286  Ashutosh Sharma  Brijesh Sharma         T Stubbs

        team_batting  team_bowling  over_number  ball_number  batter_runs  \
0                  6             1            0            0            0
1                  6             1            0            1            0
2                  6             1            0            2            0
3                  6             1            0            3            0
4                  6             1            0            4            0
...              ...           ...          ...          ...          ...
288221           252           134           18            3            1
288222           252           134           18            4            1
288223           252           134           18            5            4
288224           252           134           19            0            4
288225           252           134           19            1            0

        ...  is_bye  is_penalty wide_ball_runs no_ball_runs leg_bye_runs  \
0       ...   False       False              0            0            1
1       ...   False       False              0            0            0
2       ...   False       False              1            0            0
3       ...   False       False              0            0            0
4       ...   False       False              0            0            0
...     ...     ...         ...            ...          ...          ...
288221  ...   False       False              0            0            0
288222  ...   False       False              0            0            0
288223  ...   False       False              0            0            0
288224  ...   False       False              0            0            0
288225  ...   False       False              0            1            0

       bye_runs  penalty_runs  wicket_kind  is_super_over  innings
0             0             0          NaN          False        1
1             0             0          NaN          False        1
2             0             0          NaN          False        1
3             0             0          NaN          False        1
4             0             0          NaN          False        1
...         ...           ...          ...            ...      ...
288221        0             0          NaN          False        2
288222        0             0          NaN          False        2
288223        0             0          NaN          False        2
288224        0             0          NaN          False        2
288225        0             0          NaN          False        2

[288226 rows x 30 columns]>

*📌 Remember: Try solving without hints first. Look at hints only when genuinely stuck.*

# batsman_type            239
# bowler_type             339
# player_out           273886
# fielders_involved    273886
# wicket_kind          273886

In [499]:
#Handling Nan values

# Handling nan in 'batsman_type'
ipl['batsman_type'] = ipl['batsman_type'].fillna('Unknown')

#Handling nan in 'bowler type'
ipl['bowler_type'] = ipl['bowler_type'].fillna('Unknown')
ipl[ipl['bowler_type'] =='Part time']['bowler_type']

#Handling nan in 'player out'
ipl['player_out'] = ipl['player_out'].fillna('Not out')

#Handling nan in 'Fielders involved'
ipl['fielders_involved'] = ipl['fielders_involved'].fillna('No Filder')

#Handling nan in 'Wicket kind'
ipl['wicket_kind'] = ipl['wicket_kind'].fillna('No Wicket')

print("null values \n")
print(pd.isnull(ipl).sum())

ipl['total_runs']

null values

season_id            0
match_id             0
batter               0
bowler               0
non_striker          0
team_batting         0
team_bowling         0
over_number          0
ball_number          0
batter_runs          0
extras               0
total_runs           0
batsman_type         0
bowler_type          0
player_out           0
fielders_involved    0
is_wicket            0
is_wide_ball         0
is_no_ball           0
is_leg_bye           0
is_bye               0
is_penalty           0
wide_ball_runs       0
no_ball_runs         0
leg_bye_runs         0
bye_runs             0
penalty_runs         0
wicket_kind          0
is_super_over        0
innings              0
dtype: int64

0         1
1         0
2         1
3         0
4         0
         ..
288221    1
288222    1
288223    4
288224    4
288225    1
Name: total_runs, Length: 288226, dtype: int64

In [500]:
print(ipl['total_runs'].sum())
print(ipl['batter_runs'].sum() + ipl['extras'].sum())

389928
389928

In [502]:
ipl['total_runs'] == ipl['batter_runs'] + ipl['extras']

# Validation
#1. total runs = batter runs + extras
print("total runs = batter runs + extras", ipl['total_runs'].sum() ==ipl['batter_runs'].sum() + ipl['extras'].sum())

total runs = batter runs + extras True

Step 4 : Feature Engineering

In [518]:
# ipl['Is_Four']
ipl['Is_Four']= ipl['batter_runs'] == 4


#Is six
ipl['Is_six']= ipl['batter_runs'] == 6
ipl

# Is Dot
ipl['Is_Dot'] = (ipl['batter_runs'] == 0) & (ipl['is_wicket'] == False )

# innenings

condition = [
    ipl['over_number'] <=6 ,
    ipl['over_number'] <=14,
    ipl['over_number'] <=19
]

choices=['Power play','Middle Overs','Death overs']
ipl['Inning_phase']= np.select(condition, choices, default = None)
ipl

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,Is_Four,Is_six,Is_Dot,Inning_phase
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,0,0,0,...,1,0,0,Runs Scored,False,1,False,False,True,Power play
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,1,0,...,0,0,0,Runs Scored,False,1,False,False,True,Power play
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,2,0,...,0,0,0,Runs Scored,False,1,False,False,True,Power play
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,3,0,...,0,0,0,Runs Scored,False,1,False,False,True,Power play
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,4,0,...,0,0,0,Runs Scored,False,1,False,False,True,Power play
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288221,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,252,134,18,3,1,...,0,0,0,Runs Scored,False,2,False,False,False,Death overs
288222,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,252,134,18,4,1,...,0,0,0,Runs Scored,False,2,False,False,False,Death overs
288223,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,252,134,18,5,4,...,0,0,0,Runs Scored,False,2,True,False,False,Death overs
288224,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,252,134,19,0,4,...,0,0,0,Runs Scored,False,2,True,False,False,Death overs
288225,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,252,134,19,1,0,...,0,0,0,Runs Scored,False,2,False,False,True,Death overs